{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact Premier League\",\"MatchRecord\",\"Dim Team Lookup\",\"GetImageURL\",\"CSVExpand\",\"PLDates\",\"Dim Calendar\",\"AddMatchNumber\",\"Dim Match Number\",\"Dim H-A\",\"Fact Point Penalties\",\"Dim Team Result\",\"Dim Opposition\",\"Dim Goals Scored\",\"Dim Goals Conceded\",\"Dim Match Goals\",\"Dim Match Result\",\"Team_Lookup\",\"Dim Away Team\",\"Dim Home Team\",\"Metrics\",\"Tooltip Team Lookup\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "MatchRecord",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(Match)=>",
          "let",
          "    #\"Inserted Merged Column\" = Table.AddColumn(Match, \"Score\", each Text.Combine({Text.From([FTHG], \"en-GB\"), Text.From([FTAG], \"en-GB\")}, \" - \"), type text),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Inserted Merged Column\",{\"Date\", \"HomeTeam\", \"AwayTeam\", \"FTHG\", \"FTAG\", \"FTR\", \"HS\", \"AS\", \"HST\", \"AST\", \"HF\", \"AF\", \"HC\", \"AC\", \"HY\", \"AY\", \"HR\", \"AR\", \"Score\"}),",
          "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Removed Other Columns\", \"HomeTeam\", \"Team\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"FTHG\", \"TeamGoalsScored\"}, {\"FTAG\", \"TeamGoalsConceded\"}, {\"HS\", \"TeamShots\"}, {\"AS\", \"TeamShotsConceded\"}, {\"HST\", \"TeamShotsOnTarget\"}, {\"AST\", \"TeamShotsOnTargetConceded\"}, {\"HF\", \"TeamFouls\"}, {\"AF\", \"OpponentFouls\"}, {\"HC\", \"TeamCorners\"}, {\"AC\", \"TeamCornersConceded\"}, {\"HY\", \"TeamYellowCards\"}, {\"AY\", \"OpponentYellowCards\"}, {\"HR\", \"TeamRedCards\"}, {\"AR\", \"OpponentRedCards\"}}),",
          "    #\"HomeRecord\" = Table.AddColumn(#\"Renamed Columns\", \"Result\", each if [FTR] = null then \"P\" else if [FTR]=\"H\" then \"W\" else if [FTR]=\"D\" then \"D\" else \"L\",type text),",
          "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Removed Other Columns\", \"AwayTeam\", \"Team\"),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Duplicated Column2\",{{\"FTAG\", \"TeamGoalsScored\"}, {\"FTHG\", \"TeamGoalsConceded\"}, {\"AS\", \"TeamShots\"}, {\"HS\", \"TeamShotsConceded\"}, {\"AST\", \"TeamShotsOnTarget\"}, {\"HST\", \"TeamShotsOnTargetConceded\"}, {\"AF\", \"TeamFouls\"}, {\"HF\", \"OpponentFouls\"}, {\"AC\", \"TeamCorners\"}, {\"HC\", \"TeamCornersConceded\"}, {\"AY\", \"TeamYellowCards\"}, {\"HY\", \"OpponentYellowCards\"}, {\"AR\", \"TeamRedCards\"}, {\"HR\", \"OpponentRedCards\"}}),",
          "    #\"AwayRecord\" = Table.AddColumn(#\"Renamed Columns2\", \"Result\", each if [FTR] = null then \"P\" else if [FTR]=\"H\" then \"L\" else if [FTR]=\"D\" then \"D\" else \"W\",type text),",
          "    #\"MatchRecord\" = Table.Combine({#\"HomeRecord\", #\"AwayRecord\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"MatchRecord\",{{\"Date\", type date}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type\", {\"Team\"}, {{\"Details\", each _, type table [Date=nullable date, HomeTeam=nullable text, AwayTeam=nullable text, TeamGoalsScored=nullable text, TeamGoalsConceded=nullable text, FTR=nullable text, TeamShots=nullable text, TeamShotsConceded=nullable text, TeamShotsOnTarget=nullable text, TeamShotsOnTargetConceded=nullable text, TeamFouls=nullable text, OpponentFouls=nullable text, TeamCorners=nullable text, TeamCornersConceded=nullable text, TeamYellowCards=nullable text, OpponentYellowCards=nullable text, TeamRedCards=nullable text, OpponentRedCards=nullable text, Score=text, Team=nullable text, Result=text]}}),",
          "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Grouped Rows\", \"AddMatchNumber\", each AddMatchNumber([Details])),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Invoked Custom Function\",{\"Details\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "f89595d8-2988-4dd1-a35f-cebc1919cd83"
      },
      {
        "name": "GetImageURL",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(URL)=>",
          "let",
          "    Source = Table.FromColumns({Lines.FromBinary(Web.Contents(URL))}),",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.Contains([Column1], \"srcset=\")),",
          "    #\"Extracted Text After Delimiter\" = Table.TransformColumns(#\"Filtered Rows\", {{\"Column1\", each Text.AfterDelimiter(_, \"srcset=\"), type text}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Extracted Text After Delimiter\",\"\"\"\",\"\",Replacer.ReplaceText,{\"Column1\"}),",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\">\",\"\",Replacer.ReplaceText,{\"Column1\"}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value1\", \"Custom\", each \"https:\"&[Column1]),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Added Custom\",{\"Custom\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "6210ba35-b41c-41ad-bd7f-d3a101f993f6"
      },
      {
        "name": "CSVExpand",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(Parameter1 as binary) => let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\",  Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "0f68e581-4dbe-494c-b823-6bd76a7cc3a7"
      },
      {
        "name": "AddMatchNumber",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(TeamGroupings)=>",
          "let",
          "    #\"Added Custom\" = Table.AddColumn(TeamGroupings, \"Custom\", each if [Result] = \"P\" then 1 else 0),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Added Custom\",{{\"Custom\", Order.Ascending}, {\"Date\", Order.Ascending}}),",
          "    #\"Added Index\" = Table.AddIndexColumn(#\"Sorted Rows\", \"Match Number\", 1, 1, Int64.Type),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Index\",{\"Custom\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "604cbd02-66db-4fed-851d-b66796287b76"
      },
      {
        "name": "PLDates",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\krishan.patel\\OneDrive - University of London\\Lookup\\PL_Dates.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"First Date\", type date}, {\"Last Date\", type date}, {\"Season\", type text}, {\"Number of Relegations\", Int64.Type}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "29ea1c11-5f71-46b4-9d09-3775207d0700"
      },
      {
        "name": "Team_Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
          "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
          "    #\"dbo_Dim Team Lookup\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Team Lookup\"]}[Data]",
          "in",
          "    #\"dbo_Dim Team Lookup\""
        ],
        "kind": "m",
        "lineageTag": "4aab911f-8b7d-4d53-b5fa-c08fd2b6857a",
        "queryGroup": "Team Lookup"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Team Lookup"
      }
    ],
    "relationships": [
      {
        "name": "e3e53079-b8b9-4c58-9737-273be553a02c",
        "fromColumn": "Match Number",
        "fromTable": "Fact Premier League",
        "toColumn": "Match Number",
        "toTable": "Dim Match Number"
      },
      {
        "name": "533c7326-a7c7-4d1b-89f2-691ab0b4c32c",
        "fromColumn": "TeamIsHome",
        "fromTable": "Fact Premier League",
        "toColumn": "Home / Away",
        "toTable": "Dim H-A"
      },
      {
        "name": "63faf9dd-ebf1-43dd-b57e-b7ed43f64088",
        "fromColumn": "Result",
        "fromTable": "Fact Premier League",
        "toColumn": "Result",
        "toTable": "Dim Team Result"
      },
      {
        "name": "e8ad2d5f-f5f8-4a13-962b-1a1a62f43dad",
        "fromColumn": "TeamGoalsConceded",
        "fromTable": "Fact Premier League",
        "toColumn": "TeamGoalsConceded",
        "toTable": "Dim Goals Conceded"
      },
      {
        "name": "02ab876f-61f8-4b28-94b7-e7a5f729a623",
        "fromColumn": "TeamGoalsScored",
        "fromTable": "Fact Premier League",
        "toColumn": "TeamGoalsScored",
        "toTable": "Dim Goals Scored"
      },
      {
        "name": "d83aa406-a7fd-4d2c-954d-0a3a8a6c3ed2",
        "fromColumn": "TotalGoalsInMatch",
        "fromTable": "Fact Premier League",
        "toColumn": "TotalGoalsInMatch",
        "toTable": "Dim Match Goals"
      },
      {
        "name": "3ef053da-7e9b-145e-9965-68f457fb97d6",
        "fromColumn": "Full_Time_Result",
        "fromTable": "Fact Premier League",
        "toColumn": "Result",
        "toTable": "Dim Match Result"
      },
      {
        "name": "f0fab645-c95f-813c-8f99-ed442dad865a",
        "fromColumn": "Team",
        "fromTable": "Fact Premier League",
        "toColumn": "Team",
        "toTable": "Dim Team Lookup"
      },
      {
        "name": "64b7a5ee-2878-4c63-c72a-8d0cd3650b9b",
        "fromColumn": "Team",
        "fromTable": "Fact Point Penalties",
        "toColumn": "Team",
        "toTable": "Dim Team Lookup"
      },
      {
        "name": "9a3d4190-3134-3fbe-c134-b6cb16ca4506",
        "fromColumn": "Opposition",
        "fromTable": "Fact Premier League",
        "toColumn": "Opponent",
        "toTable": "Dim Opposition"
      },
      {
        "name": "4730b294-d4a2-fe80-ad14-13e963921287",
        "fromColumn": "Home_Team",
        "fromTable": "Fact Premier League",
        "toColumn": "Home Team",
        "toTable": "Dim Home Team"
      },
      {
        "name": "fbf763cc-3c4f-d4f8-5ac5-6502fa9a968c",
        "fromColumn": "Away_Team",
        "fromTable": "Fact Premier League",
        "toColumn": "Away Team",
        "toTable": "Dim Away Team"
      },
      {
        "name": "3fa05981-83d1-2cf8-0564-2d020a1ea25c",
        "fromColumn": "Match_Number",
        "fromTable": "Fact Point Penalties",
        "toColumn": "Match Number",
        "toTable": "Dim Match Number"
      },
      {
        "name": "96f598de-7f60-ffc3-72ef-b942174d30d6",
        "fromColumn": "Match_Date",
        "fromTable": "Fact Premier League",
        "toColumn": "Date",
        "toTable": "Dim Calendar"
      },
      {
        "name": "60eaa2e2-074f-4ce1-0444-73d7c1ca29e1",
        "fromColumn": "Date",
        "fromTable": "Fact Point Penalties",
        "toColumn": "Date",
        "toTable": "Dim Calendar"
      },
      {
        "name": "cf30cbd1-66cb-afab-ab55-4a9c116bb37f",
        "fromColumn": "Team",
        "fromTable": "Dim Team Lookup",
        "toColumn": "Team",
        "toTable": "Tooltip Team Lookup"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Dim Team Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "ImageURL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "79f27f52-31be-4663-98b3-6070d7359dc2",
            "sourceColumn": "ImageURL",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe949360-eb8c-42a6-8583-1766a8665a79",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Abbreviations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58aa03d9-baf8-4913-8048-e101b9fed02a",
            "sourceColumn": "Abbreviations",
            "summarizeBy": "none"
          },
          {
            "name": "TeamColours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12c42d88-9dbb-4243-8c16-a843d460e858",
            "sourceColumn": "TeamColours",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "04e05ab1-4fba-4961-9b88-2e9334a4d6f7",
        "partitions": [
          {
            "name": "Dim Team Lookup-5918458c-1b92-4e02-8427-2cc2d5974f21",
            "mode": "import",
            "queryGroup": "Team Lookup",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Team Lookup\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Team Lookup\"]}[Data]",
                "in",
                "    #\"dbo_Dim Team Lookup\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Premier League",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "TeamGoalsScored",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cc2790e9-8b80-4c59-93a0-1083a989a931",
            "sourceColumn": "TeamGoalsScored",
            "summarizeBy": "none"
          },
          {
            "name": "TeamGoalsConceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8383e599-9d91-49ba-8557-4f94a34aa03d",
            "sourceColumn": "TeamGoalsConceded",
            "summarizeBy": "none"
          },
          {
            "name": "TeamShots",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe7d2c0c-789a-4a11-8a3b-27ba60a6652a",
            "sourceColumn": "TeamShots",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamShotsConceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c62f0e36-1b20-4bed-a686-65c5779e31ce",
            "sourceColumn": "TeamShotsConceded",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamShotsOnTarget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b70212d6-366b-49a7-b263-813d9fcd51c4",
            "sourceColumn": "TeamShotsOnTarget",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamShotsOnTargetConceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "553b2d0b-2128-4a48-85a0-efdfb067a45c",
            "sourceColumn": "TeamShotsOnTargetConceded",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamFouls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ccbe629c-9796-4590-80a9-045dfce53bd5",
            "sourceColumn": "TeamFouls",
            "summarizeBy": "sum"
          },
          {
            "name": "OpponentFouls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b1dbacd3-6b8d-4eae-9fb2-d9a7b9a77919",
            "sourceColumn": "OpponentFouls",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamCorners",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5a86fd36-9e91-43a0-92c7-f12493d69c51",
            "sourceColumn": "TeamCorners",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamCornersConceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6e02bcc8-07d0-480f-8b72-53896ea6cb8f",
            "sourceColumn": "TeamCornersConceded",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamYellowCards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81ddba39-a9b6-41b1-a108-f6ad9ce07983",
            "sourceColumn": "TeamYellowCards",
            "summarizeBy": "sum"
          },
          {
            "name": "OpponentYellowCards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6a3596ce-8b90-4a1b-9552-b1f798e26cbe",
            "sourceColumn": "OpponentYellowCards",
            "summarizeBy": "sum"
          },
          {
            "name": "TeamRedCards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7a23e6de-adf7-493a-9903-51bef760e232",
            "sourceColumn": "TeamRedCards",
            "summarizeBy": "sum"
          },
          {
            "name": "OpponentRedCards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "05196056-ba2a-4ef9-b06b-751768c67d4a",
            "sourceColumn": "OpponentRedCards",
            "summarizeBy": "sum"
          },
          {
            "name": "Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cee0470b-0b9e-454a-9179-e7bf5a5478f9",
            "sourceColumn": "Score",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "09afd180-6167-4eb9-a6d7-5ebb24749ddd",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0e764fde-f42d-4339-b7a9-771fc2f8ab04",
            "sourceColumn": "Result",
            "summarizeBy": "none"
          },
          {
            "name": "Match Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "348fd68e-4718-4e07-a5f6-6db8226412fd",
            "sourceColumn": "Match Number",
            "summarizeBy": "none"
          },
          {
            "name": "TeamIsHome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a8a6afc4-16a2-459f-900a-511fe9e5e9b4",
            "sourceColumn": "TeamIsHome",
            "summarizeBy": "none"
          },
          {
            "name": "TotalGoalsInMatch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ebad40a-a66d-46f1-bce0-aec3a8a70251",
            "sourceColumn": "TotalGoalsInMatch",
            "summarizeBy": "none"
          },
          {
            "name": "Season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9bf27990-e12a-438a-8459-4d350b4638a7",
            "sourceColumn": "Season",
            "summarizeBy": "none"
          },
          {
            "name": "Match_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "363ed8b6-2af4-46b9-a69b-7d5445e873ea",
            "sourceColumn": "Match_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Home_Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cac8a382-fc58-40cb-8c17-ea5ee7b752f9",
            "sourceColumn": "Home_Team",
            "summarizeBy": "none"
          },
          {
            "name": "Away_Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f381b266-3671-434b-b29c-229303f5cbcf",
            "sourceColumn": "Away_Team",
            "summarizeBy": "none"
          },
          {
            "name": "Full_Time_Result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a7f56b8-6569-420d-80a3-cac44434ab92",
            "sourceColumn": "Full_Time_Result",
            "summarizeBy": "none"
          },
          {
            "name": "Opposition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "98eca714-2bb6-485c-bd9a-e27a5f07027a",
            "sourceColumn": "Opposition",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4687ce87-062a-4c8e-8317-1ebac1215ed5",
        "measures": [
          {
            "name": "Goal Scored",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Goal Scored",
            "expression": "SUM('Fact Premier League'[TeamGoalsScored])",
            "formatString": "#,0",
            "lineageTag": "80420a48-d48b-4f4a-92fe-c2ee72976c58"
          },
          {
            "name": "Goal Scored Per Game",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Goal Scored",
            "expression": "DIVIDE([Goal Scored],[Games Played])",
            "formatString": "0.00",
            "lineageTag": "c763047f-fa50-4774-afe3-c9726bdae449"
          },
          {
            "name": "Losses",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Losses",
            "expression": "CALCULATE([Games Played],'Fact Premier League'[Result]=\"L\") + IF([Games Played],0)",
            "formatString": "0",
            "lineageTag": "e3e91b09-13ac-4f1f-8436-9265fea823d3"
          },
          {
            "name": "Rank",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Position",
            "expression": [
              "IF([Games Played (End of Season)],",
              "RANKX(ALL('Dim Team Lookup'),[TiebreakScoring],,DESC,Skip))"
            ],
            "formatString": "0",
            "lineageTag": "918bf56c-4701-4c68-8740-b1a69c54b139"
          },
          {
            "name": "Rank Season End",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Position",
            "expression": "CALCULATE([Rank],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), REMOVEFILTERS('Dim Match Number'))",
            "formatString": "0",
            "lineageTag": "b2fba803-1de4-4b15-88eb-df7e4e1e9894"
          },
          {
            "name": "Rank Goal Conceded",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Goals",
            "expression": [
              "VAR MaxGoalConceded = CALCULATE([Goal Conceded],REMOVEFILTERS())",
              "",
              "RETURN",
              "",
              "IF([Games Played],",
              "RANKX(ALL('Dim Team Lookup'),IF([Games Played]=0,MaxGoalConceded,[Goal Conceded]),,ASC,Skip))"
            ],
            "formatString": "0",
            "lineageTag": "83ef4902-f049-4c76-b8cf-b928be47e82f"
          },
          {
            "name": "Rank Goal Scored",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Goals",
            "expression": "RANKX(ALL('Dim Team Lookup'),[Goal Scored],,DESC,Skip)",
            "formatString": "0",
            "lineageTag": "dd629c26-d627-469c-8a71-8b71fdfa1e89"
          },
          {
            "name": "Rank Previous Day",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Position",
            "expression": [
              "IF([Games Played],",
              "RANKX(ALL('Dim Team Lookup'),[TiebreakScoring Previous Day],,DESC,Skip))"
            ],
            "formatString": "0",
            "lineageTag": "395f5878-2cb9-4be7-a891-cb6ab22e0abb"
          },
          {
            "name": "Rank Shots",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Shots",
            "expression": "RANKX(ALL('Dim Team Lookup'),[Shots],,DESC,Skip)",
            "formatString": "0",
            "lineageTag": "b6e7d2a9-c92e-4fa8-bc8e-eec1ded041d6"
          },
          {
            "name": "Rank Shots Conceded",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Shots",
            "expression": [
              "VAR MaxShots = ",
              "CALCULATE(",
              "    [Shots Conceded],",
              "    REMOVEFILTERS())",
              "    RETURN",
              "IF([Games Played],",
              "RANKX(ALL('Dim Team Lookup'),if([Games Played]=0,MaxShots,[Shots Conceded]),,ASC,Skip))"
            ],
            "formatString": "0",
            "lineageTag": "feb16244-fff7-42bb-b776-2ee624ff22fd"
          },
          {
            "name": "Rank Shots Season End",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Shots",
            "expression": "CALCULATE([Rank Shots],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
            "formatString": "0",
            "lineageTag": "3f2be26f-947a-44eb-9892-2fa43e761934"
          },
          {
            "name": "Rank Shots Conceded Season End",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Shots",
            "expression": "CALCULATE([Rank Shots Conceded],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
            "formatString": "0",
            "lineageTag": "35d4cd81-e21d-479a-8348-f418cf2760cd"
          },
          {
            "name": "Red Cards (text)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Text Measures",
            "expression": "\"Red Cards\"",
            "lineageTag": "594d49f7-92c2-4191-9324-d7e21a60bf61"
          },
          {
            "name": "Shots (text)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Text Measures",
            "expression": "\"Shots\"",
            "lineageTag": "5242297c-d912-4775-84db-4fef63a50681"
          },
          {
            "name": "Shots on Target (text)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Text Measures",
            "expression": "\"Shots on Target\"",
            "lineageTag": "818e920f-eb81-40ea-af54-0aa85f60bdd4"
          },
          {
            "name": "Shots Conceded Per Game",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Shots Conceded Stats",
            "expression": "DIVIDE([Shots Conceded],[Games Played])",
            "formatString": "0.00",
            "lineageTag": "a79ee02c-1d37-4671-93bf-e0cb6ea5dc36"
          },
          {
            "name": "Shots Per Game",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Shots Stats",
            "expression": "DIVIDE([Shots],CALCULATE([Games Played], NOT(ISBLANK('Fact Premier League'[TeamShots]))))",
            "formatString": "0.00",
            "lineageTag": "3284cfde-bbd3-4922-8362-cd36a5697d6e"
          },
          {
            "name": "TiebreakScoring",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "TiebreakScoring",
            "expression": [
              "VAR LargestAbsGoalDifference = CALCULATE([Goal Scored] + [Goal Conceded],REMOVEFILTERS())",
              "",
              "VAR BaseToAdd = POWER(10,CEILING(LOG10(LargestAbsGoalDifference),1))*2",
              "",
              "VAR GD = BaseToAdd + [Goal Difference]",
              "",
              "VAR GS = BaseToAdd + [Goal Scored]",
              "",
              "VAR PointPenalties = CALCULATE(COUNTROWS('Fact Premier League'),REMOVEFILTERS())*3 + CALCULATE(SUM('Fact Point Penalties'[Points]), REMOVEFILTERS())",
              "",
              "VAR BaseToAdd2 = POWER(10,CEILING(LOG10(PointPenalties),1))*2",
              "",
              "VAR Points = [Points] + ABS(CALCULATE([Penalty Points],REMOVEFILTERS()))",
              "",
              "VAR RESULT = INT(Points&GD&GS)",
              "",
              "VAR GamesThisSeason = ",
              "CALCULATE([Games Played (End of Season)],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), REMOVEFILTERS('Dim Match Number'), REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              "",
              "RETURN",
              "IF(GamesThisSeason,RESULT)"
            ],
            "formatString": "0",
            "lineageTag": "5f661ef7-e0e9-4c84-ad62-c20fe9d7bec9"
          },
          {
            "name": "TiebreakScoring Previous Day",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "TiebreakScoring",
            "expression": [
              "VAR LargestAbsGoalDifference = CALCULATE([Goal Scored] + [Goal Conceded],REMOVEFILTERS())",
              "",
              "VAR BaseToAdd = POWER(10,CEILING(LOG10(LargestAbsGoalDifference),1))*2",
              "",
              "VAR GD = BaseToAdd + CALCULATE([Goal Difference],DATEADD('Dim Calendar'[Date],-1,DAY))",
              "",
              "VAR GS = BaseToAdd + CALCULATE([Goal Scored],DATEADD('Dim Calendar'[Date],-1,DAY))",
              "",
              "VAR Points = CALCULATE([Points],DATEADD('Dim Calendar'[Date],-1,DAY)) + ABS(CALCULATE([Penalty Points],REMOVEFILTERS()))",
              "",
              "VAR RESULT = INT(Points&GD&GS)",
              "",
              "RETURN",
              "IF([Games Played (End of Season)],RESULT)"
            ],
            "formatString": "0",
            "lineageTag": "95670da9-c80a-44fc-983b-8d5ac159d9e9"
          },
          {
            "name": "Points",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Points",
            "expression": "[Draws]+[Wins]*3 + [Penalty Points]",
            "formatString": "#,0",
            "lineageTag": "91730d64-44ae-439e-ae52-a3bb748ca542"
          },
          {
            "name": "Shots Season End",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Shots Stats",
            "expression": "CALCULATE([Shots],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
            "formatString": "0",
            "lineageTag": "ab90f0ac-7a3a-4b91-a4cd-f31bba34e683"
          },
          {
            "name": "Shots Conceded Season End",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Shots Conceded Stats",
            "expression": "CALCULATE([Shots Conceded], ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
            "formatString": "#,0",
            "lineageTag": "6626c04e-7a2e-4c9c-a692-5deecf247c04"
          },
          {
            "name": "Shots",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Shots Stats",
            "expression": "SUM('Fact Premier League'[TeamShots])",
            "formatString": "#,0",
            "lineageTag": "48b6ad87-4f83-4b41-b2bf-9398fb80f036"
          },
          {
            "name": "Shots Conceded",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Shots Conceded Stats",
            "expression": "SUM('Fact Premier League'[TeamShotsConceded])",
            "formatString": "#,0",
            "lineageTag": "7a2f2c88-cacc-4dee-8f71-1b5606e88150"
          },
          {
            "name": "Shots On Target",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Shots Stats",
            "expression": "SUM('Fact Premier League'[TeamShotsOnTarget])",
            "formatString": "#,0",
            "lineageTag": "8d535a7b-260c-4c82-8821-c0bb36c19910"
          },
          {
            "name": "Shots On Target Conceded",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Shots Conceded Stats",
            "expression": "SUM('Fact Premier League'[TeamShotsOnTargetConceded])",
            "formatString": "#,0",
            "lineageTag": "4ee1e22b-3211-46a0-9134-9276dbacd07c"
          },
          {
            "name": "Wins",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Wins",
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "        'Fact Premier League'[Result]=\"W\") + ",
              "        IF([Games Played],0)"
            ],
            "formatString": "0",
            "lineageTag": "6d1a9301-729e-4890-ab76-3b1998cd7e15"
          },
          {
            "name": "Yellow Cards (text)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Text Measures",
            "expression": "\"Yellow Cards\"",
            "lineageTag": "2cdd1587-e418-49de-808e-8eb9881ca839"
          },
          {
            "name": "Abs Change In Rank",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Position",
            "expression": "ABS([Change In Rank])",
            "formatString": "0",
            "lineageTag": "1d062a24-a9cf-4707-a2b4-767d9d2d8885"
          },
          {
            "name": "Change In Rank",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Ranking Position",
            "expression": "[Rank (Cumulative)]-[Rank Previous Day (Cumulative)]",
            "formatString": "0",
            "lineageTag": "7ae2465e-fa5f-46ff-a469-d6682141b566"
          },
          {
            "name": "Corners (text)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Text Measures",
            "expression": "\"Corners\"",
            "lineageTag": "25b3b6f5-e581-434d-b5d3-b70846d6bfbe"
          },
          {
            "name": "Draws",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Draws",
            "expression": "CALCULATE([Games Played],'Fact Premier League'[Result]=\"D\") + IF([Games Played]>0,0)",
            "formatString": "0",
            "lineageTag": "2741b221-b117-4432-b70b-150e6c865aa0"
          },
          {
            "name": "Fouls (text)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Text Measures",
            "expression": "\"Fouls\"",
            "lineageTag": "8630be73-f860-461c-a423-3e172526d06a"
          },
          {
            "name": "Games Played",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": "COUNTROWS(FILTER('Fact Premier League', [Full_Time_Result] <> \"P\"))",
            "formatString": "#,0",
            "lineageTag": "9b6cde78-89dc-4bdb-96cf-f1760a0e6560"
          },
          {
            "name": "Goal Conceded",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Goal Conceded",
            "expression": "SUM('Fact Premier League'[TeamGoalsConceded])",
            "formatString": "0",
            "lineageTag": "ed07d66d-b374-4835-9c22-0cd728c6961f"
          },
          {
            "name": "Goal Conceded Per Game",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Goal Conceded",
            "expression": "DIVIDE([Goal Conceded],[Games Played])",
            "formatString": "0.00",
            "lineageTag": "533f26e6-96f5-4a74-838a-5cc134ae62df"
          },
          {
            "name": "Goal Difference",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Goal Difference",
            "expression": "[Goal Scored]-[Goal Conceded]",
            "formatString": "+#,#;-#,#;0",
            "lineageTag": "a32f942c-c875-434e-95f4-a62b98803800"
          },
          {
            "name": "Title for \"Away Team Name\"",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Title",
            "expression": [
              "-- used in Head2Head page",
              "CALCULATE( ",
              "FIRSTNONBLANK('Fact Premier League'[Away_Team],1),",
              "REMOVEFILTERS('Dim Team Lookup'))"
            ],
            "lineageTag": "aac2da5e-7749-456a-a66d-6946aa8d4ac8"
          },
          {
            "name": "TiebreakScoring (Cumulative)",
            "displayFolder": "TiebreakScoring",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "",
              "VAR LargestAbsGoalDifference = CALCULATE([Goal Scored] + [Goal Conceded],REMOVEFILTERS())",
              "",
              "VAR BaseToAdd = POWER(10,CEILING(LOG10(LargestAbsGoalDifference),1))*2",
              "",
              "VAR GD = BaseToAdd + CALCULATE([Goal Difference],DatesToBeSelected, MatchesToBeSelected)",
              "",
              "VAR GS = BaseToAdd + CALCULATE([Goal Scored],DatesToBeSelected, MatchesToBeSelected)",
              " ",
              "VAR Points = CALCULATE([Points],DatesToBeSelected, MatchesToBeSelected) + ABS(CALCULATE([Penalty Points],REMOVEFILTERS()))",
              "",
              "VAR GamesThisSeason = ",
              "CALCULATE([Games Played (End of Season)],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), REMOVEFILTERS('Dim Match Number'))",
              "",
              "VAR RESULT = INT(Points&GD&GS)",
              "",
              "RETURN",
              "IF(GamesThisSeason,RESULT)"
            ],
            "formatString": "0",
            "lineageTag": "05eab7da-d0b4-4292-ae2e-f8768863148c"
          },
          {
            "name": "Rank (Cumulative)",
            "displayFolder": "Ranking Position",
            "expression": [
              "IF([Games Played (End of Season)],",
              "RANKX(ALL('Dim Team Lookup'),[TiebreakScoring (Cumulative)],,DESC,Skip))"
            ],
            "formatString": "0",
            "lineageTag": "c3d56466-e1ae-4423-b399-54ab1922e66c"
          },
          {
            "name": "Games for Season (based on TeamsInCurrentSeason)",
            "displayFolder": "Games Played",
            "expression": "(([TeamsInCurrentSeason]-1)*2)*[TeamsInCurrentSeason]",
            "formatString": "0",
            "lineageTag": "ddcf2cdb-e277-40fc-acee-843c4ac1a146"
          },
          {
            "name": "Home Team (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Home\"",
            "lineageTag": "2ca610d9-b558-4427-a68f-2b5c4098d6b9"
          },
          {
            "name": "Away Team (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Away\"",
            "lineageTag": "bd7edbc6-84e9-4b31-984a-0052a702deae"
          },
          {
            "name": "Date of Match (text)",
            "displayFolder": "Text Measures",
            "expression": [
              "CALCULATE(",
              "\"Date of Match: \"&FORMAT(MIN('Fact Premier League'[Match_Date]), \"dd mmmm yyyy\"),",
              "REMOVEFILTERS('Dim Calendar'[Has_A_Result_Date]))"
            ],
            "lineageTag": "a827a728-09ab-4d17-9ceb-d88306b0b7be"
          },
          {
            "name": "Correct Score (text)",
            "displayFolder": "Text Measures",
            "expression": [
              "VAR Score = FIRSTNONBLANK('Fact Premier League'[Score],1)",
              "RETURN",
              "IF(Score <> \"\",",
              "\"Final Score: \"&Score, \"\")"
            ],
            "lineageTag": "fa3a8435-97c8-4aa6-93fe-d5c1396c23f3"
          },
          {
            "name": "Team Corners",
            "displayFolder": "Corners",
            "expression": "SUM('Fact Premier League'[TeamCorners])",
            "formatString": "0",
            "lineageTag": "763f73c7-7825-499e-9eff-c3143bd767a0"
          },
          {
            "name": "Opponent Corners",
            "displayFolder": "Corners",
            "expression": "SUM('Fact Premier League'[TeamCornersConceded])",
            "formatString": "0",
            "lineageTag": "8b5f9862-d45b-440b-802a-f22d80d2749c"
          },
          {
            "name": "Yellow Cards Received",
            "displayFolder": "Yellow Cards",
            "expression": "SUM('Fact Premier League'[TeamYellowCards])",
            "formatString": "0",
            "lineageTag": "b8583596-8d7e-415f-b417-06edb73fc6b5"
          },
          {
            "name": "Yellow Card for Opponents",
            "displayFolder": "Yellow Cards",
            "expression": "SUM('Fact Premier League'[OpponentYellowCards])",
            "formatString": "0",
            "lineageTag": "9d7ff1d8-ab94-4451-b363-fd50f2053a1d"
          },
          {
            "name": "Red Cards Received",
            "displayFolder": "Red Cards",
            "expression": "SUM('Fact Premier League'[TeamRedCards])",
            "formatString": "0",
            "lineageTag": "e4ed388a-3520-40d1-92fe-57a8893bc8cc"
          },
          {
            "name": "Red Cards (Opponents)",
            "displayFolder": "Red Cards",
            "expression": "SUM('Fact Premier League'[OpponentRedCards])",
            "formatString": "0",
            "lineageTag": "f8392061-0664-4e21-b3d4-f6056c5402de"
          },
          {
            "name": "Final Score ()",
            "displayFolder": "Results by Season",
            "expression": [
              "VAR HomeTeam = VALUES('Dim Home Team'[Abbreviations])",
              "",
              "VAR AwayTeam = VALUES('Dim Away Team'[Abbreviations])",
              "",
              "VAR GamesPlayedThisSeason = ",
              "CALCULATE(",
              "[Games Played],",
              "REMOVEFILTERS('Dim Away Team'),",
              "REMOVEFILTERS('Dim Home Team'),",
              "HomeTeam = 'Dim Team Lookup'[Abbreviations])",
              "",
              "RETURN",
              "COALESCE(LASTNONBLANK('Fact Premier League'[Score],1), ",
              "IF(HomeTeam = AwayTeam && GamesPlayedThisSeason > 0, \" \"))"
            ],
            "lineageTag": "7f352fbb-b886-4599-807a-cc555c80faaf"
          },
          {
            "name": "Conditional Format (Match Result)",
            "displayFolder": "Results by Season",
            "expression": [
              "VAR HomeTeam = ",
              "SELECTEDVALUE('Dim Home Team'[Abbreviations])",
              "",
              "VAR AwayTeam = ",
              "SELECTEDVALUE('Dim Away Team'[Abbreviations])",
              "",
              "RETURN",
              "IF(",
              " HomeTeam = AwayTeam ,",
              "\"Light Grey\",",
              "SWITCH(",
              "LASTNONBLANK('Fact Premier League'[Full_Time_Result],1),",
              "\"H\", \"Light Blue\",",
              "\"D\", \"light Yellow\",",
              "\"A\", \"#F5C2C1\"))"
            ],
            "lineageTag": "badf0849-a467-4aa0-8449-6fa12c36ea61"
          },
          {
            "name": "Points (Cumulative)",
            "displayFolder": "Points",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = [Start Date Of Season]",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "",
              "VAR Points = ",
              "CALCULATE([Points],",
              "DatesToBeSelected,",
              "MatchesToBeSelected",
              ")",
              "",
              "RETURN",
              "Points"
            ],
            "formatString": "0",
            "lineageTag": "fc244338-c551-4db9-8f06-6b0a108da15d"
          },
          {
            "name": "Points as Text",
            "displayFolder": "Points",
            "expression": [
              "SWITCH(",
              "    [Draws]+[Wins]*3,",
              "    3, \"W\",",
              "    1, \"D\",",
              "    0, \"L\")"
            ],
            "lineageTag": "d992835b-78f0-4635-a544-d88f50f6b8fa"
          },
          {
            "name": "Points Text (Conditional Format)",
            "displayFolder": "Points",
            "expression": [
              "SWITCH(",
              "[Points (without Penalty)] ,",
              "3, \"Light Green\",",
              "1, \"light Yellow\",",
              "0, \"#F5C2C1\")"
            ],
            "lineageTag": "c672f665-507d-4ee6-bff9-8d8c7498ef1e"
          },
          {
            "name": "Score Frequency",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Score Frequency",
            "expression": "COUNTROWS(SUMMARIZE('Fact Premier League','Fact Premier League'[Match_Date],'Fact Premier League'[Home_Team],'Fact Premier League'[Away_Team]))",
            "formatString": "0",
            "lineageTag": "ca83c913-d597-4078-8548-4e71b140eb44"
          },
          {
            "name": "Score Frequency %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Score Frequency",
            "expression": "DIVIDE([Score Frequency],CALCULATE([Score Frequency],REMOVEFILTERS('Fact Premier League'[Score])))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7a977038-3376-449b-b1d3-19ec05914f27"
          },
          {
            "name": "Score Frequency to Odds",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Score Frequency",
            "expression": "DIVIDE(1,([Score Frequency %]))",
            "lineageTag": "6872dcf6-b286-4ce5-acf6-7a89de6c2eda"
          },
          {
            "name": "Games Played (Cumulative)",
            "displayFolder": "Games Played",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Games Played],",
              "    MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "formatString": "0",
            "lineageTag": "cae02011-21ee-434a-a661-ac35ebe06938"
          },
          {
            "name": "Wins (Except Season)",
            "displayFolder": "Wins",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Wins],",
              "    MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "formatString": "0",
            "lineageTag": "17b3a256-e59d-4104-9fe1-8b830e3ccaa7"
          },
          {
            "name": "Draws (Cumulative)",
            "displayFolder": "Draws",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "",
              "RETURN",
              "CALCULATE(",
              " [Draws],",
              " MatchesToBeSelected,",
              "DatesToBeSelected)"
            ],
            "formatString": "0",
            "lineageTag": "c9bf5fb8-f768-49b6-b9a8-f2925743cea1"
          },
          {
            "name": "Losses (Cumulative)",
            "displayFolder": "Losses",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "RETURN",
              "CALCULATE(",
              "    [Losses],",
              "   MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "formatString": "0",
            "lineageTag": "40af70b1-ebe4-4586-acc8-3562ea2076e5"
          },
          {
            "name": "Goal Difference (Cumulative)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Goal Difference",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "RETURN",
              "CALCULATE(",
              "    [Goal Difference],",
              "    MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "formatString": "+#,#;-#,#;0",
            "lineageTag": "60b32b65-7b38-4293-92a2-efa41329aeb7"
          },
          {
            "name": "Goal Conceded (Cumulative)",
            "displayFolder": "Goal Conceded",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "RETURN",
              "CALCULATE(",
              "    [Goal Conceded],",
              "    MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "formatString": "0",
            "lineageTag": "da80feea-3ba0-4fa1-9e1d-4983eb408f53"
          },
          {
            "name": "Goal Scored (Cumulative)",
            "displayFolder": "Goal Scored",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "RETURN",
              "CALCULATE(",
              "    [Goal Scored],",
              "    MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "formatString": "0",
            "lineageTag": "0c4d2cbd-1092-4b36-9974-bf005ce16058"
          },
          {
            "name": "Rank Previous Day (Cumulative)",
            "displayFolder": "Ranking Position",
            "expression": [
              "IF([Games Played (End of Season)],",
              "RANKX(ALL('Dim Team Lookup'),[TiebreakScoring Previous Day (Cumulative)],,DESC,Skip))"
            ],
            "formatString": "0",
            "lineageTag": "5495f9bb-f01f-4e95-84e4-f4955f24179b"
          },
          {
            "name": "Rank Previous Season End",
            "displayFolder": "Ranking Position",
            "expression": [
              "VAR CurrentSeason = MAX('Dim Calendar'[Season])",
              "VAR LastSeason = ",
              "MAXX(",
              "    FILTER(ALL('Dim Calendar'[Season]),",
              "CurrentSeason > [Season] && [Season] <> \"None\"),",
              "[Season])",
              "VAR LastSeasonRank = ",
              "CALCULATE(",
              "    [Rank],",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    REMOVEFILTERS('Dim Match Number'),",
              "    'Dim Calendar'[Season] = LastSeason)",
              "RETURN",
              "IF([Rank Season End],",
              "IF(LastSeasonRank, LastSeasonRank, \"P\"))"
            ],
            "formatString": "0",
            "lineageTag": "a9d720c3-6ddd-4036-809c-973785cf2ebd"
          },
          {
            "name": "Conditional Format (Rank Previous Season End)",
            "displayFolder": "Ranking Position",
            "expression": [
              "VAR RankOfTeam = ",
              "[Rank Previous Season End]",
              "",
              "VAR WinningTeam = ",
              "RankOfTeam  = 1",
              "",
              "VAR RunnerUpTeam = ",
              "RankOfTeam  = 2",
              "",
              "VAR UEFAPositions = ",
              "RankOfTeam  IN {3,4}",
              "",
              "VAR ExtraUEFAPosition = ",
              "RankOfTeam  = 5",
              "",
              "VAR RelegationTeams = ",
              "RankOfTeam = \"P\"",
              "",
              "RETURN",
              "SWITCH(TRUE(),",
              "WinningTeam , \"Gold\",",
              "RunnerUpTeam, \"Silver\",",
              "UEFAPositions, \"Light Green\",",
              "ExtraUEFAPosition, \"Light Blue\",",
              "RelegationTeams, \"#BF9DFC\")"
            ],
            "lineageTag": "dfc16c96-6cba-4479-93b5-4c031e5d824b"
          },
          {
            "name": "Title: (In Season Position Tooltip)",
            "displayFolder": "Title",
            "expression": "LASTNONBLANK('Dim Calendar'[Season],1)&\" \"&FIRSTNONBLANK('Dim Team Lookup'[Team],1)",
            "lineageTag": "77feb889-3254-43ff-ba24-754b76825689"
          },
          {
            "name": "Total Goals Per Game",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Total Goals",
            "expression": "[Goal Conceded Per Game] + [Goal Scored Per Game]",
            "formatString": "0.00",
            "lineageTag": "97076aa4-b6d6-4306-b5df-a5ae1e9b1fcc"
          },
          {
            "name": "TiebreakScoring Previous Day (Cumulative)",
            "displayFolder": "TiebreakScoring",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])-1",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])-1",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "",
              "VAR LargestAbsGoalDifference = CALCULATE([Goal Scored] + [Goal Conceded],REMOVEFILTERS())",
              "",
              "VAR BaseToAdd = POWER(10,CEILING(LOG10(LargestAbsGoalDifference),1))*2",
              "",
              "VAR GD = BaseToAdd + CALCULATE([Goal Difference],DatesToBeSelected, MatchesToBeSelected)",
              "",
              "VAR GS = BaseToAdd + CALCULATE([Goal Scored],DatesToBeSelected, MatchesToBeSelected)",
              " ",
              "VAR Points = CALCULATE([Points],DatesToBeSelected, MatchesToBeSelected) + ABS(CALCULATE([Penalty Points],REMOVEFILTERS()))",
              "",
              "VAR GamesThisSeason = ",
              "CALCULATE([Games Played (End of Season)],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), REMOVEFILTERS('Dim Match Number'))",
              "",
              "VAR RESULT = INT(Points&GD&GS)",
              "",
              "RETURN",
              "IF(GamesThisSeason,RESULT)"
            ],
            "formatString": "0",
            "lineageTag": "7dbc4f22-c82e-4070-b139-9cf13351ac98"
          },
          {
            "name": "Both Teams To Score",
            "displayFolder": "Games Played",
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "    'Fact Premier League'[TeamGoalsConceded] > 0,",
              "    'Fact Premier League'[TeamGoalsScored] > 0)"
            ],
            "formatString": "0",
            "lineageTag": "1db83280-1c54-4e68-83e3-ce844235f229"
          },
          {
            "name": "Draw %",
            "displayFolder": "Draws",
            "expression": "DIVIDE([Draws],[Games Played])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5371c1dc-2b93-43de-84ad-32ddc02f1603"
          },
          {
            "name": "Loss%",
            "displayFolder": "Losses",
            "expression": "DIVIDE([Losses],[Games Played])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "294d3981-c7e8-4ed4-8943-73cbe09edee5"
          },
          {
            "name": "Win %",
            "displayFolder": "Wins",
            "expression": "DIVIDE([Wins],[Games Played])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "88492b00-40e9-48cd-a8b6-0b21eaf73337"
          },
          {
            "name": "Away Games",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "    'Dim H-A'[Home / Away]=\"Away\")"
            ],
            "formatString": "#,0",
            "lineageTag": "2f552785-d14a-4b55-91aa-384cb6ecc3ce"
          },
          {
            "name": "Home Games",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "    'Dim H-A'[Home / Away]=\"Home\")"
            ],
            "formatString": "#,0",
            "lineageTag": "0ce4a5a3-dad1-44f6-a0e9-52a5be3fd62c"
          },
          {
            "name": "0 Games Ago Result",
            "displayFolder": "Games Ago",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = [Start Date Of Season]",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[Match_Date],'Fact Premier League'[Result]),",
              "DatesToBeSelected)",
              "",
              "VAR RemovePMatches = ",
              "--FILTER(",
              "MatchesInContext",
              "-- ,[Result] <> \"P\")",
              "",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(RemovePMatches,",
              "\"Rank\",",
              "RANKX(RemovePMatches,[Match_Date],,DESC))",
              "",
              "VAR TextResult = ",
              "    SUMMARIZE(FILTER(AddRank, [Rank] = 1), [Result])",
              "",
              "    RETURN",
              "SWITCH(TextResult,",
              "\"W\",3,",
              "\"D\",1,",
              "\"L\",0,",
              "\"P\",2)"
            ],
            "formatString": "0",
            "lineageTag": "bee87732-50f4-427a-9f22-ed5f036e2ee1"
          },
          {
            "name": "1 Games Ago Result",
            "displayFolder": "Games Ago",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = [Start Date Of Season]",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[Match_Date],'Fact Premier League'[Result]),",
              "DatesToBeSelected)",
              "",
              "VAR RemovePMatches = ",
              "--FILTER(",
              "MatchesInContext",
              "-- ,[Result] <> \"P\")",
              "",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(RemovePMatches,",
              "\"Rank\",",
              "RANKX(RemovePMatches,[Match_Date],,DESC))",
              "",
              "VAR TextResult = ",
              "    SUMMARIZE(FILTER(AddRank, [Rank] = 2), [Result])",
              "",
              "    RETURN",
              "",
              "SWITCH(TextResult,",
              "\"W\",3,",
              "\"D\",1,",
              "\"L\",0,",
              "\"P\",2)"
            ],
            "formatString": "0",
            "lineageTag": "93911dc1-3e51-454f-9596-f9f2bf5215bc"
          },
          {
            "name": "2 Games Ago Result",
            "displayFolder": "Games Ago",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = [Start Date Of Season]",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[Match_Date],'Fact Premier League'[Result]),",
              "DatesToBeSelected)",
              "",
              "VAR RemovePMatches = ",
              "--FILTER(",
              "MatchesInContext",
              "-- ,[Result] <> \"P\")",
              "",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(RemovePMatches,",
              "\"Rank\",",
              "RANKX(RemovePMatches,[Match_Date],,DESC))",
              "",
              "VAR TextResult = ",
              "    SUMMARIZE(FILTER(AddRank, [Rank] = 3), [Result])",
              "",
              "    RETURN",
              "",
              "SWITCH(TextResult,",
              "\"W\",3,",
              "\"D\",1,",
              "\"L\",0,",
              "\"P\",2)"
            ],
            "formatString": "0",
            "lineageTag": "9602c424-2779-4459-97f2-822c6d511593"
          },
          {
            "name": "3 Games Ago Result",
            "displayFolder": "Games Ago",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = [Start Date Of Season]",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[Match_Date],'Fact Premier League'[Result]),",
              "DatesToBeSelected)",
              "",
              "VAR RemovePMatches = ",
              "--FILTER(",
              "MatchesInContext",
              "-- ,[Result] <> \"P\")",
              "",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(RemovePMatches,",
              "\"Rank\",",
              "RANKX(RemovePMatches,[Match_Date],,DESC))",
              "",
              "VAR TextResult = ",
              "    SUMMARIZE(FILTER(AddRank, [Rank] = 4), [Result])",
              "",
              "    RETURN",
              "",
              "SWITCH(TextResult,",
              "\"W\",3,",
              "\"D\",1,",
              "\"L\",0,",
              "\"P\",2)"
            ],
            "formatString": "0",
            "lineageTag": "e0095493-3829-4208-8a65-b8d1681b2008"
          },
          {
            "name": "4 Games Ago Result",
            "displayFolder": "Games Ago",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = [Start Date Of Season]",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[Match_Date],'Fact Premier League'[Result]),",
              "DatesToBeSelected)",
              "",
              "VAR RemovePMatches = ",
              "--FILTER(",
              "MatchesInContext",
              "-- ,[Result] <> \"P\")",
              "",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(RemovePMatches,",
              "\"Rank\",",
              "RANKX(RemovePMatches,[Match_Date],,DESC))",
              "",
              "VAR TextResult = ",
              "    SUMMARIZE(FILTER(AddRank, [Rank] = 5), [Result])",
              "",
              "    RETURN",
              "",
              "SWITCH(TextResult,",
              "\"W\",3,",
              "\"D\",1,",
              "\"L\",0,",
              "\"P\",2)"
            ],
            "formatString": "0",
            "lineageTag": "b6fe2708-e8b1-45d5-8994-5d94d9359fa8"
          },
          {
            "name": "Away Draw",
            "displayFolder": "Away Results",
            "expression": [
              "CALCULATE(",
              "    [Draws],",
              "'Dim H-A'[Home / Away] = \"Away\")"
            ],
            "formatString": "0",
            "lineageTag": "5d9a603c-73ae-4dec-8639-f42b5f907393"
          },
          {
            "name": "Away Losses",
            "displayFolder": "Away Results",
            "expression": [
              "CALCULATE(",
              "    [losses],",
              "'Dim H-A'[Home / Away] = \"Away\")"
            ],
            "formatString": "0",
            "lineageTag": "9622d676-09fa-49ef-a54a-3da0975050b1"
          },
          {
            "name": "Away Win %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Results",
            "expression": "DIVIDE([Away Wins],[Unique Games Played])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "a73129d9-e763-4451-9349-e811a29667d2"
          },
          {
            "name": "Away Wins",
            "displayFolder": "Away Results",
            "expression": [
              "CALCULATE(",
              "    [Wins],",
              "'Dim H-A'[Home / Away] = \"Away\")"
            ],
            "formatString": "0",
            "lineageTag": "38365486-74f0-451b-a1f4-0af9ecbe16c7"
          },
          {
            "name": "Home Win %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Results",
            "expression": "DIVIDE([Home Wins],[Unique Games Played])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "508e2120-bcbc-4a15-af11-a1ee88c87ecc"
          },
          {
            "name": "Home Draws",
            "displayFolder": "Home Results",
            "expression": [
              "CALCULATE(",
              "    [Draws],",
              "'Dim H-A'[Home / Away] = \"Home\")"
            ],
            "formatString": "0",
            "lineageTag": "974df291-60ee-4e17-be46-9e0eb8a1b1c1"
          },
          {
            "name": "Home Wins",
            "displayFolder": "Home Results",
            "expression": [
              "CALCULATE(",
              "    [Wins],",
              "'Dim H-A'[Home / Away] = \"Home\")"
            ],
            "formatString": "0",
            "lineageTag": "56e66b3e-9aec-4482-a2d7-ec4194a68f06"
          },
          {
            "name": "Home Losses",
            "displayFolder": "Home Results",
            "expression": [
              "CALCULATE(",
              "    [losses],",
              "'Dim H-A'[Home / Away] = \"Home\")"
            ],
            "formatString": "0",
            "lineageTag": "a7bfc97f-c9d2-4891-b212-760f6f55e91a"
          },
          {
            "name": "Total Draws",
            "displayFolder": "Results",
            "expression": [
              "VAR PremTable = ",
              "SUMMARIZE(",
              "    FILTER('Fact Premier League', [Full_Time_Result] = \"D\"),",
              "    'Fact Premier League'[Match_Date],",
              " 'Fact Premier League'[Home_Team],",
              " 'Fact Premier League'[Away_Team])",
              "",
              " RETURN",
              "",
              " COUNTROWS(PremTable)"
            ],
            "formatString": "0",
            "lineageTag": "edb7663d-b206-4572-a49c-225134c2703d"
          },
          {
            "name": "Total Draw %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Results",
            "expression": "DIVIDE([Total Draws],[Unique Games Played])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "fa68e605-10fd-480b-b968-6586447c1347"
          },
          {
            "name": "Unique Games Played",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": [
              "VAR Games =",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match_Date],'Fact Premier League'[Home_Team],'Fact Premier League'[Away_Team])",
              "",
              "VAR NumberOfGames = ",
              "COUNTROWS(games)",
              "",
              "return",
              "",
              "NumberOfGames"
            ],
            "formatString": "#,0",
            "lineageTag": "8d05d269-d027-42c6-a932-7c95a6463e1b"
          },
          {
            "name": "Unique Games Played (where stats avaliable)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": [
              "VAR Games =",
              "SUMMARIZE(",
              "    FILTER('Fact Premier League',",
              "    'Fact Premier League'[TeamShots] <> BLANK()),",
              "    'Fact Premier League'[Match_Date],'Fact Premier League'[Home_Team],'Fact Premier League'[Away_Team])",
              "",
              "VAR NumberOfGames = ",
              "COUNTROWS(games)",
              "",
              "return",
              "",
              "NumberOfGames"
            ],
            "formatString": "#,0",
            "lineageTag": "fd1508b5-e6b6-46c5-b60c-a202e479bd19"
          },
          {
            "name": "Start Date Of Season",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Calendar",
            "expression": "CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
            "formatString": "Long Date",
            "lineageTag": "e1ebdbc8-5a0c-46cc-adeb-39730bc5fb69"
          },
          {
            "name": "Away Points Per Game",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Points",
            "expression": [
              "CALCULATE(",
              "    [Points Per Game (without Penalty)],",
              "    'Dim H-A'[Home / Away] = \"Away\")"
            ],
            "lineageTag": "e9b115c7-ccec-4a7c-bcda-56dd8713e3df"
          },
          {
            "name": "Conditional Format (Rank Cumulative)",
            "displayFolder": "Ranking Position",
            "expression": [
              "VAR TeamsInCurrentSeason = ",
              "[TeamsInCurrentSeason]",
              "",
              "VAR RelegationNumbers = ",
              "IF(SELECTEDVALUE('Dim Calendar'[Season]) = \"1994 - 95\", 4, 3)",
              "",
              "VAR RankOfTeam = [Rank (Cumulative)]",
              "",
              "VAR RelegationTeams =",
              "RankOfTeam >",
              "(TeamsInCurrentSeason - RelegationNumbers)",
              "",
              "VAR WinningTeam = ",
              "RankOfTeam  = 1",
              "",
              "VAR RunnerUpTeam = ",
              "RankOfTeam  = 2",
              "",
              "VAR UEFAPositions = ",
              "RankOfTeam  IN {3,4}",
              "",
              "VAR ExtraUEFAPosition = ",
              "RankOfTeam  = 5",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    WinningTeam , \"Gold\",",
              "    RunnerUpTeam, \"Silver\",",
              "    UEFAPositions, \"Light Green\",",
              "    ExtraUEFAPosition, \"Light Blue\",",
              "    RelegationTeams, \"#F5C2C1\")"
            ],
            "lineageTag": "520c48f6-b974-446a-90a3-e5e415763ae2"
          },
          {
            "name": "Home Advantage (Home Points Per Game - Away Points Per Game)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Points",
            "expression": [
              "CALCULATE(",
              "[Home Points Per Game] - [Away Points Per Game],",
              "REMOVEFILTERS('Dim H-A'))"
            ],
            "lineageTag": "f4508d2b-3e03-45fa-a0c2-3a0159be3b26"
          },
          {
            "name": "Home Points Per Game",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Points",
            "expression": [
              "CALCULATE(",
              "    [Points Per Game (without Penalty)],",
              "    'Dim H-A'[Home / Away] = \"Home\")"
            ],
            "lineageTag": "c09067fc-2a01-4f45-b30f-ac903a1083db"
          },
          {
            "name": "Results By Season (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Results By Season\"",
            "lineageTag": "dea0c97f-4806-4e9d-8311-4cadfb70909c"
          },
          {
            "name": "Points Per Game (without Penalty)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Points",
            "expression": "DIVIDE([Points (without Penalty)],[Games Played])",
            "formatString": "0.00",
            "lineageTag": "b2b49f5b-cdaa-42cf-a13d-901478804ff7"
          },
          {
            "name": "Points (without Penalty)",
            "displayFolder": "Points",
            "expression": "[Wins]*3+[Draws]",
            "formatString": "0",
            "lineageTag": "51cb2c28-99a7-4399-a4f4-84d3c72a36ad"
          },
          {
            "name": "Points (End of Season)",
            "displayFolder": "Points",
            "expression": "CALCULATE([Points],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), REMOVEFILTERS('Dim Match Number'))",
            "formatString": "0",
            "lineageTag": "2f76129e-256f-4990-b304-ba37383152b7"
          },
          {
            "name": "Goal Scored Per Game (Cumulative)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Goal Scored",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "RETURN",
              "CALCULATE(",
              "    [Goal Scored Per Game],",
              "    MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "lineageTag": "bf559552-4434-44f4-8fd3-cd1cbfa39304"
          },
          {
            "name": "Points Per Game (without Penalty) (Cumulative)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Points",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "",
              "VAR Points = ",
              "CALCULATE([Points Per Game (without Penalty)],",
              "DatesToBeSelected,",
              "MatchesToBeSelected",
              ")",
              "",
              "RETURN",
              "Points"
            ],
            "lineageTag": "f9ef1a00-e861-4588-9e78-441c7b47b167"
          },
          {
            "name": "Goal Conceded Per Game (Cumulative)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Goal Conceded",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR BeginingDateOfSeason = CALCULATE(MIN('Dim Calendar'[Date]),ALLEXCEPT('Dim Calendar', 'Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] <= MaxDate",
              "    && 'Dim Calendar'[Date] >= BeginingDateOfSeason)",
              "",
              "VAR MaxMatchNumber = MAX('Dim Match Number'[Match Number])",
              "",
              "VAR MatchesToBeSelected = FILTER(ALL('Dim Match Number'[Match Number]),",
              "    'Dim Match Number'[Match Number] <= MaxMatchNumber)",
              "RETURN",
              "CALCULATE(",
              "    [Goal Conceded Per Game],",
              "    MatchesToBeSelected,",
              "    DatesToBeSelected)"
            ],
            "lineageTag": "d296b7ea-9868-467b-9db9-63cbdb9d5c24"
          },
          {
            "name": "Filter by Date (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Filter by Date\"",
            "lineageTag": "09b539e3-7271-4cd0-97e8-12b877d527fc"
          },
          {
            "name": "Offical Score",
            "displayFolder": "Score Frequency",
            "expression": "LASTNONBLANK('Fact Premier League'[Score],1)",
            "lineageTag": "c7c4cb91-ab82-483b-a00e-dab44fe41d68"
          },
          {
            "name": "Both Teams To Score %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": "DIVIDE([Both Teams To Score],[Games Played])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "93d72905-6540-49dd-b98a-bce2dfac4a3b"
          },
          {
            "name": "Date Error Warning - Icon Color",
            "displayFolder": "Premier League Table (Data Warning for Date)",
            "expression": "IF([Games Played (Cumulative)],\"rgba(179, 179, 179,0)\", \"rgba(255, 0, 0,1)\" )",
            "lineageTag": "22e47590-79da-4ce2-978b-118c7c8c0cd9"
          },
          {
            "name": "Date Error Warning - tooltip",
            "displayFolder": "Premier League Table (Data Warning for Date)",
            "expression": "IF([Games Played (Cumulative)], \" \", \"Please select a valid date in the current season by altering the day/month filters!\")",
            "lineageTag": "ba79fb70-d016-482a-9e3d-a27e9f6021b0"
          },
          {
            "name": "Goals (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Goals\"",
            "lineageTag": "abed41f3-e052-4937-97a3-9d4afcb5637c"
          },
          {
            "name": "Median Goals In Match",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Total Goals",
            "expression": "MEDIAN('Fact Premier League'[TotalGoalsInMatch])",
            "formatString": "0.00",
            "lineageTag": "8fac5866-3ed0-4e9b-96f3-995d7b5de649"
          },
          {
            "name": "Points Per Game",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Points",
            "expression": "DIVIDE([Points],[Games Played])",
            "lineageTag": "3c78e865-f17e-423c-b72e-4030ec928078"
          },
          {
            "name": "Points (Last Season)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Points",
            "expression": [
              "VAR CurrentSeason = MAX('Dim Calendar'[Season])",
              "VAR LastSeason = ",
              "MAXX(",
              "    FILTER(ALL('Dim Calendar'[Season]),",
              "CurrentSeason > [Season] && [Season] <> \"None\"),",
              "[Season])",
              "VAR LastSeasonPoints = ",
              "CALCULATE(",
              "    [Points Per Game],",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Dim Calendar'[Season] = LastSeason)",
              "RETURN",
              "IF([Rank Season End], LastSeasonPoints)"
            ],
            "lineageTag": "37a1aea9-ab88-43aa-b932-0602f500bd58"
          },
          {
            "name": "Games Played (End of Season)",
            "displayFolder": "Games Played",
            "expression": "CALCULATE([Games Played],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]),REMOVEFILTERS('Dim Match Number'))",
            "formatString": "0",
            "lineageTag": "4973d282-14de-4cdc-ab45-bd88beb9c66a"
          },
          {
            "name": "TeamsInCurrentSeason",
            "displayFolder": "Games Played",
            "expression": [
              "CALCULATE(",
              "    COUNTROWS(VALUES('Fact Premier League'[Team])),",
              "ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), ",
              "REMOVEFILTERS('Dim Team Lookup'), ",
              "REMOVEFILTERS('Dim Match Number'))"
            ],
            "formatString": "0",
            "lineageTag": "b6f43965-c45f-4485-9cb8-773fdd2687db"
          },
          {
            "name": "Away Goals Per Game (Trend)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Goal Conceded Per Game]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)]",
              ")"
            ],
            "lineageTag": "e10f3c06-c01b-4f01-a9be-079d5350d9d6"
          },
          {
            "name": "Away Points Per Game (Trend)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Away Points Per Game]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)])"
            ],
            "lineageTag": "8ca311df-32d0-491f-9e0d-9dc2f291b084"
          },
          {
            "name": "Away Team To Score (Trend)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Percentage (1 or more Away Goals)]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)]",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "113ddb15-ff41-4223-93b5-52263bd7b6b8"
          },
          {
            "name": "Home Advantage (Trend)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Home Advantage (Home Points Per Game - Away Points Per Game)]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)])"
            ],
            "lineageTag": "495b04be-3250-4da2-9a4b-aaacd566e65c"
          },
          {
            "name": "Home Goals Per Game (Trend)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Goal Scored Per Game]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)]",
              ")"
            ],
            "lineageTag": "33322077-b3e5-4c74-b390-f5a349dc892f"
          },
          {
            "name": "Home Points Per Game (Trend)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Home Points Per Game]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)])"
            ],
            "lineageTag": "b8f4236a-4649-4c8a-bda7-fe86eb2c0b24"
          },
          {
            "name": "Home Team To Score (Trend)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Percentage (1 or more Home Goals)]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)]",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7f625150-a78c-4cfe-9fdd-dc1434b2d05d"
          },
          {
            "name": "Season (as number for Trends)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "IF([Games Played],",
              "RANKX(ALL('Dim Calendar'[Season]),LASTNONBLANK('Dim Calendar'[Season],[Games Played]),,ASC))"
            ],
            "lineageTag": "b2286a3b-8b0f-4f1b-b2e1-9becedc83f92"
          },
          {
            "name": "Games Played (All Match Result)",
            "displayFolder": "Games Played",
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Match Result'))"
            ],
            "formatString": "0",
            "lineageTag": "34a07790-cff0-498e-90e6-c87f50708d3b"
          },
          {
            "name": "Games Played % (by Match Result)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": [
              "DIVIDE(",
              "[Games Played],",
              "[Games Played (All Match Result)]",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "62293e31-af79-4615-9262-55e5817384ad"
          },
          {
            "name": "Overall (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Overall\"",
            "lineageTag": "ec30241f-f37f-4d4d-9a15-0a3efead0509"
          },
          {
            "name": "Away (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Away\"",
            "lineageTag": "a1949381-a049-4504-a9a1-db01033ab3fa"
          },
          {
            "name": "Home (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Home\"",
            "lineageTag": "70a11486-951c-4572-b95d-9f5a90282699"
          },
          {
            "name": "Away Goals Conceded",
            "displayFolder": "Goal Conceded",
            "expression": [
              "CALCULATE(",
              "    [Goal Conceded],",
              "    'Dim H-A'[Home / Away] = \"Away\")"
            ],
            "formatString": "0",
            "lineageTag": "d2d50b0d-1ce1-4874-9e39-71af52b36fa4"
          },
          {
            "name": "Home Goals Conceded",
            "displayFolder": "Goal Conceded",
            "expression": [
              "CALCULATE(",
              "    [Goal Conceded],",
              "    'Dim H-A'[Home / Away] = \"Home\")"
            ],
            "formatString": "0",
            "lineageTag": "d8159b05-d949-43d4-93b0-ade1ff6e3a5d"
          },
          {
            "name": "Away Points",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Points",
            "expression": [
              "CALCULATE(",
              "    [Points (without Penalty)],",
              "    'Dim H-A'[Home / Away] = \"Away\")"
            ],
            "formatString": "#,0",
            "lineageTag": "c52cf1d2-9d9c-4f43-bbf7-9f4c0a417f0d"
          },
          {
            "name": "Home Points",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Points",
            "expression": [
              "CALCULATE(",
              "    [Points (without Penalty)],",
              "    'Dim H-A'[Home / Away] = \"Home\")"
            ],
            "formatString": "#,0",
            "lineageTag": "5d47f759-3ac2-4584-ae39-190f8ad3ea18"
          },
          {
            "name": "Points Per Game (title)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Title",
            "expression": "\"Points Per Game by Team\"",
            "lineageTag": "ce0fcb7f-e02b-48cd-9454-14cf3474eeb0"
          },
          {
            "name": "Points Per Game by Season (title)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Title",
            "expression": "\"Points Per Game by Season\"",
            "lineageTag": "f76b65f3-2273-425a-bd67-5b4adcdd9482"
          },
          {
            "name": "Points Spread by Season (title)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Title",
            "expression": "\"Points Spread by Season\"",
            "lineageTag": "0ab5ebeb-87d2-49f2-bfc2-39da0c9eac56"
          },
          {
            "name": "Premier League Table (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Premier League Table\"",
            "lineageTag": "76099d91-10f4-4b80-804f-c69d8e275db7"
          },
          {
            "name": "Last 5 Games (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Last 5 Games\"",
            "lineageTag": "24cba190-db8c-4877-ac98-9b7d31c7beb7"
          },
          {
            "name": "Team Goals Analysis by Season (title)",
            "displayFolder": "Title",
            "expression": "\"Team Goals Analysis by Season\"",
            "lineageTag": "19023602-fc57-4b47-baae-c47e8f372884"
          },
          {
            "name": "Goals per Match (title)",
            "displayFolder": "Title",
            "expression": "\"Goals per Match by Team\"",
            "lineageTag": "d3e903b6-fc73-410f-b641-fc3beeecdc4b"
          },
          {
            "name": "Historical Match Statistics (title)",
            "displayFolder": "Title",
            "expression": "\"Historical Match Statistics\"",
            "lineageTag": "514b4473-2b65-4060-9a9f-653b88e71345"
          },
          {
            "name": "Historical Team Performances (title)",
            "displayFolder": "Title",
            "expression": "\"Team Statisics\"",
            "lineageTag": "1b7a7590-9abb-43cf-810b-3f1ceec5ee8c"
          },
          {
            "name": "Match Result (title)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Title",
            "expression": "\"Match Results by Team\"",
            "lineageTag": "c74867d3-c13e-4e96-a381-dec5056ae1b8"
          },
          {
            "name": "Match Results by Season (title)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Title",
            "expression": "\"Match Results by Season\"",
            "lineageTag": "4a393a3c-7d5a-4064-bf47-8ae91e30078b"
          },
          {
            "name": "Results by Match Number (title)",
            "displayFolder": "Title",
            "expression": "\"Results by Match Number\"",
            "lineageTag": "901d1e4b-f1f1-433a-826e-dbf6be546faf"
          },
          {
            "name": "Games Played % (by W/D/L)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Games Played",
            "expression": [
              "VAR GamesPlayedRemovedOfResult = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Team Result'))",
              "",
              "RETURN",
              "",
              "DIVIDE([Games Played],GamesPlayedRemovedOfResult)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9315c3e1-25a8-478c-8407-be37bf6de960"
          },
          {
            "name": "Clean Sheet",
            "displayFolder": "Games Played",
            "expression": "CALCULATE([Games Played], 'Fact Premier League'[TeamGoalsConceded] = 0)",
            "formatString": "0",
            "lineageTag": "3c73e7fe-b847-472b-b1ad-a92a9169c6ec"
          },
          {
            "name": "Games Scored In",
            "displayFolder": "Games Played",
            "expression": "CALCULATE([Games Played], 'Fact Premier League'[TeamGoalsScored] > 0)",
            "formatString": "0",
            "lineageTag": "0370c359-f11d-4639-b842-aaed3f80892f"
          },
          {
            "name": "Title: (Team)",
            "displayFolder": "Title",
            "expression": "FIRSTNONBLANK('Dim Team Lookup'[Team],1)",
            "lineageTag": "b60626ea-4c1b-46e5-993c-0fa4679f91dd"
          },
          {
            "name": "Home Goal Difference",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Goal Difference",
            "expression": "CALCULATE([Goal Difference],'Dim H-A'[Home / Away] = \"Home\")",
            "formatString": "+#,#;-#,#;0",
            "lineageTag": "fe78bfbf-c86e-4f56-b544-d53061c50b3f"
          },
          {
            "name": "Away Goal Difference",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Goal Difference",
            "expression": "CALCULATE([Goal Difference],'Dim H-A'[Home / Away] = \"Away\")",
            "formatString": "+#,#;-#,#;0",
            "lineageTag": "c805b3c0-9f7b-45c7-9c5b-13299c487d8b"
          },
          {
            "name": "Previous Championship Teams (Title)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Title",
            "expression": "\"Previous Championship Teams\"",
            "lineageTag": "aee82d9e-9852-441d-a0f0-51ca8a8e006b"
          },
          {
            "name": "Previous Relegated Teams (Title)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Title",
            "expression": "\"Previous Relegated Teams\"",
            "lineageTag": "8624543e-e702-4b48-97a0-51acf91680f9"
          },
          {
            "name": "End Date Of Season",
            "displayFolder": "Calendar",
            "expression": "CALCULATE(MAX('Dim Calendar'[Date]), ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
            "formatString": "General Date",
            "lineageTag": "bb921735-d309-41bf-9513-92812b2ec15e"
          },
          {
            "name": "Next Match",
            "dataCategory": "ImageUrl",
            "displayFolder": "Next Fixture",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR EndDateOfSeason = CALCULATE(MAX('Dim Calendar'[Date]), ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] > MaxDate",
              "    && 'Dim Calendar'[Date] <= EndDateOfSeason)",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number],'Dim Opposition'[ImageURL]),",
              "DatesToBeSelected)",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(MatchesInContext,",
              "\"Rank\",",
              "RANKX(MatchesInContext,[Match Number],,ASC))",
              "",
              "VAR TextResult = ",
              "    SUMMARIZE(FILTER(AddRank, [Rank] = 1), [ImageURL])",
              "",
              "    RETURN",
              "TextResult"
            ],
            "lineageTag": "86dcd0c4-0bc1-423f-992b-3f19696d2d32"
          },
          {
            "name": "Next Match (H/A)",
            "displayFolder": "Next Fixture",
            "expression": [
              "VAR MaxDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR EndDateOfSeason = [End Date Of Season]",
              "",
              "VAR DatesToBeSelected = FILTER(ALL('Dim Calendar'[Date]),",
              "    'Dim Calendar'[Date] > MaxDate",
              "    && 'Dim Calendar'[Date] <= EndDateOfSeason)",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[TeamIsHome]),",
              "DatesToBeSelected)",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(MatchesInContext,",
              "\"Rank\",",
              "RANKX(MatchesInContext,[Match Number],,ASC))",
              "",
              "VAR TextResult = ",
              "    SUMMARIZE(FILTER(AddRank, [Rank] = 1), [TeamIsHome])",
              "",
              "    RETURN",
              "    SWITCH( TextResult,",
              "    \"Home\", \"H\",",
              "    \"Away\", \"A\")"
            ],
            "lineageTag": "6ad2a954-c702-4825-8949-4a1932a0f5c5"
          },
          {
            "name": "Match Goals Per Game (Trend)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            FILTER(",
              "            ALLSELECTED ('Dim Calendar'[Season]),",
              "             'Dim Calendar'[Season] <> \"None\"),",
              "            \"Known[X]\",[Season (as number for Trends)],",
              "            \"Known[Y]\", [Total Goals Per Game]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "RETURN",
              "    SUMX ( ",
              "        FILTER(",
              "            DISTINCT ( 'Dim Calendar'[Season] ),",
              "             'Dim Calendar'[Season] <> \"None\")",
              "        ,",
              "    Intercept + Slope * [Season (as number for Trends)]",
              ")"
            ],
            "lineageTag": "1af948cc-a1ee-4b6e-b069-e8e6e143eb6c"
          },
          {
            "name": "Match Goals Analysis by Season (title)",
            "displayFolder": "Title",
            "expression": "\"Match Goals Analysis by Season\"",
            "lineageTag": "266c8356-69b3-4288-9436-432f97bf587c"
          },
          {
            "name": "Tiebreak (without Penalty)",
            "displayFolder": "TiebreakScoring",
            "expression": [
              "VAR LargestAbsGoalDifference = CALCULATE([Goal Scored] + [Goal Conceded],REMOVEFILTERS())",
              "",
              "VAR BaseToAdd = POWER(10,CEILING(LOG10(LargestAbsGoalDifference),1))*2",
              "",
              "VAR GD = BaseToAdd + [Goal Difference]",
              "",
              "VAR GS = BaseToAdd + [Goal Scored]",
              "",
              "VAR Points = [Points (without Penalty)]",
              "",
              "VAR RESULT = INT(Points&GD&GS)",
              "",
              "VAR GamesThisSeason = ",
              "CALCULATE([Games Played (End of Season)],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), REMOVEFILTERS('Dim Match Number'), REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              "",
              "RETURN",
              "IF(GamesThisSeason,RESULT)"
            ],
            "formatString": "0",
            "lineageTag": "5fccc4df-990c-458e-bf3b-afb0d207f77f"
          },
          {
            "name": "Final Score (Default)",
            "displayFolder": "Results by Season",
            "expression": "LASTNONBLANK('Fact Premier League'[Score],1)",
            "lineageTag": "7286ffe6-a417-42c9-9c55-70154f348997"
          },
          {
            "name": "Premier League (All Season Text)",
            "displayFolder": "Text Measures",
            "expression": "\"All Season Premier League Table\"",
            "lineageTag": "2c2ee7f5-1064-4544-ad45-b37744d29e24"
          },
          {
            "name": "League Leaders by Team (text)",
            "displayFolder": "Text Measures",
            "expression": "\"Analysis of League Leaders\"",
            "lineageTag": "eeab8b59-7dd0-432c-a3bf-5a2e2223565a"
          },
          {
            "name": "Relegation Zone Analysis (title)",
            "displayFolder": "Title",
            "expression": "\"Relegation Zone Analysis\"",
            "lineageTag": "bcf1f00d-8275-4dcc-a815-534297acbff4"
          },
          {
            "name": "Premier League Report (Title)",
            "displayFolder": "Title",
            "expression": "\"Premier League Report\"",
            "lineageTag": "06ea40d2-007f-4238-a208-b9516f79a912"
          },
          {
            "name": "Krishan Patel",
            "displayFolder": "Krishan",
            "expression": "\"By Krishan Patel\"",
            "lineageTag": "43f94cb6-6817-4527-bbd2-03a15e963bd5"
          },
          {
            "name": "Home Goals Scored",
            "displayFolder": "Goal Scored",
            "expression": [
              "CALCULATE(",
              "    [Goal Scored],",
              "    'Dim H-A'[Home / Away] = \"Home\")"
            ],
            "formatString": "0",
            "lineageTag": "65c82dda-2456-4d4c-afb1-e7219700d754"
          },
          {
            "name": "Away Goals Scored",
            "displayFolder": "Goal Scored",
            "expression": [
              "CALCULATE(",
              "    [Goal Scored],",
              "    'Dim H-A'[Home / Away] = \"Away\")"
            ],
            "formatString": "0",
            "lineageTag": "5cb81e61-fe9e-42bd-88b8-bc46a8568a3c"
          },
          {
            "name": "Title: (Season)",
            "expression": "LASTNONBLANK('Dim Calendar'[Season],1)&\" Matches\"",
            "lineageTag": "5bf1f33f-5654-4b06-8ffd-dd15eff20ce1"
          },
          {
            "name": "Draw Rank (Cumulative) Marker",
            "displayFolder": "Rank (Markers)",
            "expression": [
              "IF([Draws],",
              "[Rank (Cumulative)])"
            ],
            "formatString": "0",
            "lineageTag": "5993b097-9361-4a2b-94b3-bbe8722928f1"
          },
          {
            "name": "Loss Rank (Cumulative) Marker",
            "displayFolder": "Rank (Markers)",
            "expression": [
              "IF([Losses],",
              "[Rank (Cumulative)])"
            ],
            "formatString": "0",
            "lineageTag": "ca92ba49-ab81-41b0-85be-5fc22a443a1a"
          },
          {
            "name": "Win Rank (Cumulative) Marker",
            "displayFolder": "Rank (Markers)",
            "expression": [
              "IF([Wins],",
              "[Rank (Cumulative)])"
            ],
            "formatString": "0",
            "lineageTag": "33dcccf4-8660-4d26-a936-e3b515f5c1eb"
          },
          {
            "name": "Win",
            "expression": [
              "",
              "VAR Number = [Wins]",
              "VAR Perc = [Win %]",
              "RETURN",
              "IF(Number,",
              "FORMAT(Number, \"#,###\")&\" (\"&",
              "FORMAT( Perc, \"0%\")",
              "&\")\",",
              "\"\")"
            ],
            "lineageTag": "bbfa12ae-e0be-4e19-8076-f31f68a722d3"
          },
          {
            "name": "Loss",
            "expression": [
              "",
              "VAR Number = [Losses]",
              "VAR Perc = [Loss%]",
              "RETURN",
              "IF(Number,",
              "FORMAT(Number, \"#,###\")&\" (\"&",
              "FORMAT( Perc, \"0%\")",
              "&\")\",",
              "\"\")"
            ],
            "lineageTag": "455d1c4d-7140-42cc-a9b3-1e27c79272d8"
          },
          {
            "name": "Draw",
            "expression": [
              "",
              "VAR Number = [Draws]",
              "VAR Perc = [Draw %]",
              "RETURN",
              "IF(Number,",
              "FORMAT(Number, \"#,###\")&\" (\"&",
              "FORMAT( Perc, \"0%\")",
              "&\")\",",
              "\"\")"
            ],
            "lineageTag": "ad4d353c-fadd-4d3f-a275-accd3f9eff66"
          },
          {
            "name": "Both Teams To Scored",
            "expression": [
              "",
              "VAR Number = [Both Teams To Score]",
              "VAR Perc = [Both Teams To Score %]",
              "RETURN",
              "IF(Number,",
              "FORMAT(Number, \"#,###\")&\" (\"&",
              "FORMAT( Perc, \"0%\")",
              "&\")\",",
              "\"\")"
            ],
            "lineageTag": "469ceb15-1dd9-42d0-adc3-676e93fe165c"
          }
        ],
        "partitions": [
          {
            "name": "Fact Premier League-e0e4999c-aa35-460e-aa7f-a001cfd0a910",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Fact Premier League\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Fact Premier League\"]}[Data]",
                "in",
                "    #\"dbo_Fact Premier League\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91eef031-c253-406b-b1a5-f83f6a2aab48",
            "sourceColumn": "Season",
            "summarizeBy": "none"
          },
          {
            "name": "Has_A_Result_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34335622-d70c-44cd-92b9-e62dd4130ce0",
            "sourceColumn": "Has_A_Result_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "83a2d8a6-170f-4f6a-b9f5-7b2182fe8157",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e811f0a-b15e-4989-ad20-a4623a42b42d",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "02b0ccc0-7445-419d-a40f-ee430386257b",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "000f7aeb-82a5-4407-b59b-d8a0a36f455d",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff3dfe31-d83a-4c0b-8e53-0ce7194de811",
            "sourceColumn": "Weekday",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8c5c73e-184d-4e10-be2a-94bb5058af81",
            "sortByColumn": "Month",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "9a98de70-4075-4d9c-adf5-97fc62ff8d9c",
        "measures": [
          {
            "name": "Last Updated",
            "expression": [
              "",
              "\"Last Updated: \"&",
              "FORMAT(",
              "CALCULATE(",
              "MAX('Dim Calendar'[Date]),",
              "REMOVEFILTERS(),",
              "'Dim Calendar'[Has_A_Result_Date] = \"Has Result\"),",
              "\"dd/mm/yyyy\")"
            ],
            "lineageTag": "7e8d6ccd-4f70-41af-bf80-e76c0b7f8daa"
          }
        ],
        "partitions": [
          {
            "name": "Dim Calendar-d62943d2-c8e4-4a63-8e88-bbf16069e420",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Calendar\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Calendar\"]}[Data]",
                "in",
                "    #\"dbo_Dim Calendar\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Match Number",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Match Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d66b1ae5-2e2f-4ccb-8337-320cf0a02ac4",
            "sourceColumn": "Match Number",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e5bf71af-2e2d-4843-bff2-0827d22bc6ab",
        "partitions": [
          {
            "name": "Dim Match Number-5338892d-e9a0-443d-8694-b6617551835e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Match Number\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Match Number\"]}[Data]",
                "in",
                "    #\"dbo_Dim Match Number\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim H-A",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Home / Away",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dcb51f4-930e-4970-8599-0171091ee064",
            "sortByColumn": "ID",
            "sourceColumn": "Home / Away",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e6587ca3-f18b-4075-b4c5-d96025b76572",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "867a5a4f-c66a-4669-8be1-63db8ff3cbb7",
        "partitions": [
          {
            "name": "Dim H-A-5bfeffc9-5869-48d3-9ce7-5b13ae590e0b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim H-A\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim H-A\"]}[Data]",
                "in",
                "    #\"dbo_Dim H-A\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Point Penalties",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "e0f81ace-fcc1-4ed0-956b-ee5eda85f1db",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "371dcba8-a877-4ec4-853a-7a393d0099a2",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "Points",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "87bea088-617d-4186-9183-a160eafbbdf8",
            "sourceColumn": "Points",
            "summarizeBy": "sum"
          },
          {
            "name": "Match_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4c0e0b02-1c94-4a94-ab68-f94b6ddf3db6",
            "sourceColumn": "Match_Number",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "521e7582-f1cf-4482-b016-dfae93db71c8",
        "measures": [
          {
            "name": "Penalty Points",
            "displayFolder": "Points",
            "expression": "SUM('Fact Point Penalties'[Points])",
            "formatString": "0",
            "lineageTag": "1b6f7adf-a956-470e-95ee-b290944a73d6"
          }
        ],
        "partitions": [
          {
            "name": "Fact Point Penalties-981ca9b0-2853-4b33-be63-7a6e24cf20f0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Fact Point Penalties\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Fact Point Penalties\"]}[Data]",
                "in",
                "    #\"dbo_Fact Point Penalties\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Team Result",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a3b855d6-ee59-4802-b94c-67b575f35d31",
            "sourceColumn": "Result",
            "summarizeBy": "none"
          },
          {
            "name": "Result Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c3c91c3-95f2-4360-bd7d-e1682672a428",
            "sortByColumn": "Result Id",
            "sourceColumn": "Result Name",
            "summarizeBy": "none"
          },
          {
            "name": "Result Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "246eb550-a4ce-425f-bd4a-266ebd143a5f",
            "sourceColumn": "Result Id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bb8b9ecf-4678-49a4-b6d3-157da34a2845",
        "partitions": [
          {
            "name": "Dim Team Result-5fe2cdb2-4e78-4d1b-a8e8-e86bab6e4835",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Team Result\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Team Result\"]}[Data]",
                "in",
                "    #\"dbo_Dim Team Result\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Opposition",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ImageURL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90f5cc36-b046-4c70-98bf-9df37308e194",
            "sourceColumn": "ImageURL",
            "summarizeBy": "none"
          },
          {
            "name": "Abbreviations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b716df8-6293-4861-b2cf-2aad40d507d4",
            "sourceColumn": "Abbreviations",
            "summarizeBy": "none"
          },
          {
            "name": "TeamColours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46a8d646-57e6-4c50-8663-11d5b344463e",
            "sourceColumn": "TeamColours",
            "summarizeBy": "none"
          },
          {
            "name": "Opponent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "832e24b4-9a15-4a34-a735-a4f6d907a09a",
            "sourceColumn": "Opponent",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c1365cd7-60e8-4285-9d22-e612b24908b1",
        "partitions": [
          {
            "name": "Dim Opposition-cd3b8423-31d3-484e-acb7-a8ef88f6d2a2",
            "mode": "import",
            "queryGroup": "Team Lookup",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Opposition\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Opposition\"]}[Data]",
                "in",
                "    #\"dbo_Dim Opposition\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Goals Scored",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "TeamGoalsScored",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d9b89a3-3338-418a-a192-f83aca9ab2a3",
            "sourceColumn": "TeamGoalsScored",
            "summarizeBy": "none"
          },
          {
            "name": "Over 0.5 Goals Scored",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c609b95a-89e2-4dc7-8513-24dc3d386557",
            "sourceColumn": "Over 0.5 Goals Scored",
            "summarizeBy": "none"
          },
          {
            "name": "Over 1.5 Goals Scored",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0426214a-7f97-402c-936a-491aa2547ca8",
            "sourceColumn": "Over 1.5 Goals Scored",
            "summarizeBy": "none"
          },
          {
            "name": "Over 2.5 Goals Scored",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35572d4d-2717-4700-a927-2c37d5f93f66",
            "sourceColumn": "Over 2.5 Goals Scored",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1678a3b9-9da9-4b92-a41f-600a29382722",
        "measures": [
          {
            "name": "Cumulative Goals Scored",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "'Dim Goals Scored'[TeamGoalsScored] <= MAX('Dim Goals Scored'[TeamGoalsScored]),",
              "REMOVEFILTERS('Dim Goals Scored'))"
            ],
            "formatString": "#,0",
            "lineageTag": "0279e412-f9a2-4804-b30f-13addf243632"
          },
          {
            "name": "Cumulative Goals Scored %",
            "expression": [
              "VAR GamesPlayed = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Goals Scored'))",
              "",
              "VAR CumulativeGoalsScored = [Cumulative Goals Scored]",
              "",
              "VAR  Result =",
              "DIVIDE(CumulativeGoalsScored,GamesPlayed)",
              "",
              "RETURN ",
              "Result"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a5158fa1-dfc9-4364-b39b-6d3ae7aa7b49"
          },
          {
            "name": "% GamesPlayed (By Goals Scored)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR GamesPlayed = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Goals Scored'))",
              "",
              "",
              "RETURN",
              "",
              "DIVIDE([Games Played],GamesPlayed)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4f545d5e-034b-4601-9bfa-0473aaad71d1"
          },
          {
            "name": "Percentage (1 or more Home Goals)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Number (1 or more Home Goals)],[Games Played])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "604e8dd7-2962-4827-a27e-3c400c68211e"
          },
          {
            "name": "Number (1 or more Home Goals)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "'Dim Goals Scored'[TeamGoalsScored] > 0,",
              "REMOVEFILTERS('Dim Goals Scored'))"
            ],
            "formatString": "#,0",
            "lineageTag": "ba4ee1f3-e483-493e-8ec9-3916e0173ba8"
          }
        ],
        "partitions": [
          {
            "name": "Dim Goals Scored-daafc24f-7a45-4885-96d9-d0199cb38adf",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Goal Scored\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Goal Scored\"]}[Data]",
                "in",
                "    #\"dbo_Dim Goal Scored\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Goals Conceded",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "TeamGoalsConceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb8e85c9-e604-431c-855f-004bb8aacd99",
            "sourceColumn": "TeamGoalsConceded",
            "summarizeBy": "none"
          },
          {
            "name": "Over 0.5 Goals Conceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "855bd81b-a894-4fd2-85b3-8d4e491c3306",
            "sourceColumn": "Over 0.5 Goals Conceded",
            "summarizeBy": "none"
          },
          {
            "name": "Over 1.5 Goals Conceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b30fa54a-4a6d-4f2c-8604-d502b74cc99f",
            "sourceColumn": "Over 1.5 Goals Conceded",
            "summarizeBy": "none"
          },
          {
            "name": "Over 2.5 Goals Conceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9763e099-b7ba-48fd-aa26-f1def81023ad",
            "sourceColumn": "Over 2.5 Goals Conceded",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2a313214-985f-4704-a5c3-e28412135dc4",
        "measures": [
          {
            "name": "Cumulative Goals Conceded",
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "'Dim Goals Conceded'[TeamGoalsConceded] <= MAX('Dim Goals Conceded'[TeamGoalsConceded]),",
              "REMOVEFILTERS('Dim Goals Conceded'))"
            ],
            "formatString": "0",
            "lineageTag": "4b08c12c-a639-4643-b084-d48a25b8e709"
          },
          {
            "name": "Cumulative Goals Conceded %",
            "expression": [
              "VAR GamesPlayed = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Goals Conceded'))",
              "",
              "VAR CumulativeGoalsScored = [Cumulative Goals Conceded]",
              "",
              "RETURN",
              "",
              "DIVIDE(CumulativeGoalsScored,GamesPlayed)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "81eda3a8-012d-42b5-999c-4b0c8e1948b8"
          },
          {
            "name": "% GamesPlayed (By Goals Conceded)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR GamesPlayed = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Goals Conceded'))",
              "",
              "",
              "RETURN",
              "",
              "DIVIDE([Games Played],GamesPlayed)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "802fd9df-f221-44b9-a5e5-ad27b180fcce"
          },
          {
            "name": "Percentage (1 or more Away Goals)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Number (1 or more Away Goals)],[Games Played])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4899eee7-89f5-4d44-8b6c-25ac0a194f10"
          },
          {
            "name": "Number (1 or more Away Goals)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    [Games Played],",
              "'Dim Goals Conceded'[TeamGoalsConceded] > 0,",
              "REMOVEFILTERS('Dim Goals Conceded'))"
            ],
            "formatString": "#,0",
            "lineageTag": "60f7571f-d95d-4792-9d3c-b579d98337c3"
          },
          {
            "name": "% GamesPlayed (By Goals Scored AND Goals Conceded)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR GamesPlayed = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Goals Scored'), REMOVEFILTERS('Dim Goals Conceded'))",
              "",
              "",
              "RETURN",
              "",
              "DIVIDE([Games Played],GamesPlayed)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f4c38760-8015-4084-aaa5-b566516863c9"
          },
          {
            "name": "Score?Scored?Conceded",
            "expression": [
              "VAR GoalScored = ",
              " SELECTEDVALUE('Dim Goals Scored'[TeamGoalsScored])",
              "",
              " VAR GoalConcended = ",
              " SELECTEDVALUE('Dim Goals Conceded'[TeamGoalsConceded])",
              "",
              " RETURN",
              "",
              "IF( NOT( ISBLANK(GoalScored) ) && NOT( ISBLANK(GoalConcended) ), GoalScored&\" - \"&GoalConcended,",
              "FORMAT(COALESCE(GoalScored, GoalConcended), \"General Number\"))"
            ],
            "lineageTag": "14c51b03-71cc-4a2d-a9eb-b81f568b1e84"
          },
          {
            "name": "Score?Scored?Conceded Title",
            "expression": [
              "VAR GoalScored = ",
              " SELECTEDVALUE('Dim Goals Scored'[TeamGoalsScored])",
              "",
              " VAR GoalConcended = ",
              " SELECTEDVALUE('Dim Goals Conceded'[TeamGoalsConceded])",
              "",
              " RETURN",
              "",
              "IF( NOT( ISBLANK(GoalScored) ) && NOT( ISBLANK(GoalConcended) ), \"Goals Scored - Goals Conceded\",",
              "IF( NOT( ISBLANK(GoalScored)), \"Goal Scored\",",
              "IF( NOT( ISBLANK(GoalConcended)), \"Goal Conceded\",",
              "\"\")))"
            ],
            "lineageTag": "a551d0a4-c57a-4021-8104-14acdfc4062e"
          }
        ],
        "partitions": [
          {
            "name": "Dim Goals Conceded-17888498-ed0b-4b45-a682-42b3ba896830",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Goal Conceded\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Goal Conceded\"]}[Data]",
                "in",
                "    #\"dbo_Dim Goal Conceded\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Match Goals",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "TotalGoalsInMatch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "96715f6d-d4da-4f39-a262-c9c55879c808",
            "sourceColumn": "TotalGoalsInMatch",
            "summarizeBy": "none"
          },
          {
            "name": "Over 0.5 Goals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "111d28e3-1e8f-451a-ad0e-a4dc7c697375",
            "sourceColumn": "Over 0.5 Goals",
            "summarizeBy": "none"
          },
          {
            "name": "Over 1.5 Goals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af70db4b-effb-4242-9d5b-82a8f3fe4900",
            "sourceColumn": "Over 1.5 Goals",
            "summarizeBy": "none"
          },
          {
            "name": "Over 2.5 Goals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acd2dcc5-a385-414f-b3c7-d5b2e6af7315",
            "sourceColumn": "Over 2.5 Goals",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9fbf700f-f67a-4926-9040-e21adc3323fd",
        "measures": [
          {
            "name": "Cumulative Total Goals In Match",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR MAXMATCHGOALS = CALCULATE(MAX('Fact Premier League'[TotalGoalsInMatch]),REMOVEFILTERS('Dim Match Goals'))",
              "RETURN",
              "IF(MAX('Dim Match Goals'[TotalGoalsInMatch]) <= MAXMATCHGOALS,",
              "CALCULATE(",
              "    [Games Played],",
              "'Dim Match Goals'[TotalGoalsInMatch] <= MAX('Dim Match Goals'[TotalGoalsInMatch]),",
              "REMOVEFILTERS('Dim Match Goals')))"
            ],
            "formatString": "#,0",
            "lineageTag": "7c86e2d2-393a-438e-8c3a-5508f5008bab"
          },
          {
            "name": "Cumulative Total Goals In Match %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR GamesPlayed = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Match Goals'))",
              "",
              "VAR CumulativeGoalsScored = [Cumulative Total Goals In Match]",
              "",
              "RETURN",
              "",
              "DIVIDE(CumulativeGoalsScored,GamesPlayed)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "249e81cf-65f3-4f9a-a5cd-5c9558eb45e8"
          },
          {
            "name": "% GamesPlayed (TotalGoalsInMatch)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR GamesPlayed = ",
              "CALCULATE(",
              "    [Games Played],",
              "    REMOVEFILTERS('Dim Match Goals'))",
              "",
              "",
              "RETURN",
              "",
              "DIVIDE([Games Played],GamesPlayed)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "759d2ae6-28fe-4ab4-b0cc-b57e3c978687"
          }
        ],
        "partitions": [
          {
            "name": "Dim Match Goals-65abbfc5-7d21-4db3-9822-b1e60a3b908c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Match Goals\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Match Goals\"]}[Data]",
                "in",
                "    #\"dbo_Dim Match Goals\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Match Result",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fd64165c-5bbb-4fe5-bbaa-23fa921cf9f0",
            "sortByColumn": "Result Id",
            "sourceColumn": "Result",
            "summarizeBy": "none"
          },
          {
            "name": "Result Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec405bb0-deb2-41a1-9fdd-830febfda671",
            "sortByColumn": "Result Id",
            "sourceColumn": "Result Name",
            "summarizeBy": "none"
          },
          {
            "name": "Result Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e9333bca-b882-4899-942f-145565fd32df",
            "sourceColumn": "Result Id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5ecab231-170a-4935-a6bc-78d56448978a",
        "partitions": [
          {
            "name": "Dim Match Result-e85f7f86-865e-4b86-88ee-036d0094172e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Match Result\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Match Result\"]}[Data]",
                "in",
                "    #\"dbo_Dim Match Result\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Away Team",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ImageURL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "dbd20794-c2d7-4214-96b0-d843eebfbc99",
            "sourceColumn": "ImageURL",
            "summarizeBy": "none"
          },
          {
            "name": "Abbreviations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d08f9070-d506-4495-9a98-870b34b56ab4",
            "sortByColumn": "Away Team",
            "sourceColumn": "Abbreviations",
            "summarizeBy": "none"
          },
          {
            "name": "TeamColours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ceefa1c0-61e8-4e38-9f4c-4a8f021f349d",
            "sourceColumn": "TeamColours",
            "summarizeBy": "none"
          },
          {
            "name": "Away Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c9c3783-86ce-4a59-8dc2-eaa40a6ea99c",
            "sourceColumn": "Away Team",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4dd5addf-a3f3-4243-bad9-77744d75e9a5",
        "measures": [
          {
            "name": "Away",
            "expression": "FIRSTNONBLANK('Dim Away Team'[Abbreviations],1)",
            "lineageTag": "6f7f6a01-ae4b-45bb-9866-ef0439bba057"
          },
          {
            "name": "Away Url",
            "expression": "FIRSTNONBLANK('Dim Away Team'[ImageURL],1)",
            "lineageTag": "778b7202-0be4-414f-a71e-a3792d43fd5d"
          }
        ],
        "partitions": [
          {
            "name": "Dim Away Team",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Away Team\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Away Team\"]}[Data]",
                "in",
                "    #\"dbo_Dim Away Team\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Home Team",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ImageURL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "d756b1fd-7531-476c-a53c-19502c096ac1",
            "sourceColumn": "ImageURL",
            "summarizeBy": "none"
          },
          {
            "name": "Abbreviations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "013fd008-0b8b-4ed0-b955-d352949ddd1a",
            "sortByColumn": "Home Team",
            "sourceColumn": "Abbreviations",
            "summarizeBy": "none"
          },
          {
            "name": "TeamColours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f85c3339-8724-4aed-8982-c4efa28a5a35",
            "sourceColumn": "TeamColours",
            "summarizeBy": "none"
          },
          {
            "name": "Home Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5de5d5ea-d01d-4d44-8e6e-543d3842bccd",
            "sourceColumn": "Home Team",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f174c51b-9f09-48e9-a29d-91268e4aa22f",
        "measures": [
          {
            "name": "Home",
            "expression": "FIRSTNONBLANK('Dim Home Team'[Abbreviations],1)",
            "lineageTag": "60abb00d-30f4-4b8e-a334-1c2e2cce2ae9"
          },
          {
            "name": "Home URL",
            "expression": "FIRSTNONBLANK('Dim Home Team'[ImageURL],1)",
            "lineageTag": "3778a9dd-a7ba-444f-9651-5e013501ddf9"
          }
        ],
        "partitions": [
          {
            "name": "Dim Home Team",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Dim Home Team\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Dim Home Team\"]}[Data]",
                "in",
                "    #\"dbo_Dim Home Team\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e297f22-9916-4922-81e6-0c7ef1a190d8",
            "sortByColumn": "Index",
            "sourceColumn": "Metric",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cefd29bf-39f2-4fdd-b22a-c5025ae21b16",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ad67c158-8d6e-43f5-9d99-c2e6604ce2ee",
        "measures": [
          {
            "name": "Metric Measure  (Match Number)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR SelectedMetric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN",
              "",
              "IF(",
              "ISINSCOPE('Dim Match Number'[Match Number]),",
              "IF(",
              "[Games Played],",
              "SWITCH(",
              "SelectedMetric,",
              "    \"Position\", ",
              "    FORMAT([Rank (Cumulative)], \"General Number\"),",
              "    \"Point Total\", ",
              "    FORMAT([Points (Cumulative)], \"General Number\"),",
              "    \"Result\", ",
              "    [Points as Text])),",
              "   [Rank Season End])"
            ],
            "lineageTag": "4720a411-851e-4938-8fce-bd74cf1271fc"
          },
          {
            "name": "Metric Measure (Conditional Format)",
            "expression": [
              "VAR SelectedMetric = SELECTEDVALUE(Metrics[Metric])",
              "RETURN",
              "SWITCH(SelectedMetric,",
              "\"Position\", [Conditional Format (Rank Cumulative)],",
              "\"Point Total\", [Conditional Format (Rank Cumulative)],",
              "\"Result\", [Points Text (Conditional Format)])"
            ],
            "lineageTag": "81a43d02-e806-4603-9f94-77e43c42c474"
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    dbo_Metric = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Metric\"]}[Data]",
                "in",
                "    dbo_Metric"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tooltip Team Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2ef64ae-4e8b-499a-b462-1388ca7b828a",
            "sourceColumn": "Team",
            "summarizeBy": "none"
          },
          {
            "name": "ImageURL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "f89966ca-5419-4b55-be06-a3299ae99bb6",
            "sourceColumn": "ImageURL",
            "summarizeBy": "none"
          },
          {
            "name": "Abbreviations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20ba76aa-e091-4d7c-9d5d-d2b0064be675",
            "sourceColumn": "Abbreviations",
            "summarizeBy": "none"
          },
          {
            "name": "TeamColours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "799fde7f-d0c8-40e8-abfe-ba2bc44b9b9f",
            "sourceColumn": "TeamColours",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ebe6aff3-2bcf-4f8d-9817-bf17ab631d62",
        "measures": [
          {
            "name": "Away Corners (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Away\",[TeamCorners],[TeamCornersConceded])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "01345ec4-ca58-46ec-bd2c-24be7937e406"
          },
          {
            "name": "Away Red Cards (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Away\",[TeamRedCards],[OpponentRedCards])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "867faea0-6af3-42ef-be95-431d2ae05155"
          },
          {
            "name": "Away Shots (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Away\",[TeamShots],[TeamShotsConceded])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "eac3d86d-35f7-4cd8-b82d-a2fa7e7e21be"
          },
          {
            "name": "Away Shots On Target (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Away\",[TeamShotsOnTarget],[TeamShotsOnTargetConceded])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "4138c56a-ba4d-4859-a7a8-e93d2b434469"
          },
          {
            "name": "Away Yellow Cards (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Away\",[TeamYellowCards],[OpponentYellowCards])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "2f22fc5f-e12f-4a72-ba90-049a9d0bdd84"
          },
          {
            "name": "Home Corners (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Home\",[TeamCorners],[TeamCornersConceded])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "5a53f6c5-d525-43c3-ba90-41eac1b19106"
          },
          {
            "name": "Home Red Cards (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Home\",[TeamRedCards],[OpponentRedCards])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "fbff6205-7cda-4215-b6ea-c1b9f808a5fa"
          },
          {
            "name": "Home Shots (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Home\",[TeamShots],[TeamShotsConceded])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "66a926de-be46-4a4d-b107-bbce0afbd3b6"
          },
          {
            "name": "Home Shots On Target (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Home\",[TeamShotsOnTarget],[TeamShotsOnTargetConceded])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "6a536adc-e083-4aa0-ac85-f2a6c1687a41"
          },
          {
            "name": "Home Yellow Cards (PLT)",
            "displayFolder": "Head2Head Measures (PLT)",
            "expression": [
              "VAR CurrentDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "SUMX('Fact Premier League',IF('Fact Premier League'[TeamIsHome] = \"Home\",[TeamYellowCards],[OpponentYellowCards])),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] = CurrentDate)",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "8a27722e-ac91-4e17-8999-89f0e78b0fc5"
          },
          {
            "name": "Background Colour (Visibility for Historical Position Tooltip)",
            "displayFolder": "Background Visibility",
            "expression": [
              "IF([Games Played] = 0,",
              "\"rgba(179, 179, 179,1)\", \"rgba(255, 0, 0,0)\" )"
            ],
            "lineageTag": "06ccc865-2eb8-4c98-9713-c27df9e362d2"
          },
          {
            "name": "Background Colour (Visibility for Valid H2H)",
            "displayFolder": "Background Visibility",
            "expression": "IF(FIRSTNONBLANK('Dim Away Team'[Away Team],1) = LASTNONBLANK('Dim Home Team'[Home Team],1),\"rgba(179, 179, 179,1)\", \"rgba(255, 0, 0,0)\" )",
            "lineageTag": "c6fcfeff-bfa7-4c97-a1df-fce99666e5d5"
          },
          {
            "name": "Draws (TeamToolTip)",
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "CALCULATE([Draws (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "70646fcf-3c73-43af-a661-58ff186a9a01"
          },
          {
            "name": "Games Played (TeamToolTip)",
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "CALCULATE([Games Played (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "bbdc5be8-be9f-4845-82e1-03e3d9e217db"
          },
          {
            "name": "Goal Difference (TeamToolTip)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "CALCULATE([Goal Difference (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "+#,#;-#,#;0",
            "lineageTag": "ee8c8378-0487-44e1-a61c-a7d75cb202c8"
          },
          {
            "name": "Losses (TeamToolTip)",
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "CALCULATE([Losses (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "e74acca0-7186-4729-948b-b120abbeddc2"
          },
          {
            "name": "Points (TeamToolTip)",
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "CALCULATE([Points (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "e75771e1-95a7-4221-9213-02198f11df5a"
          },
          {
            "name": "Rank with Name (TeamToolTip)",
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "VAR SelectedHomeAway = SELECTEDVALUE('Dim H-A'[Home / Away])",
              "",
              "RETURN",
              "",
              "CALCULATE([Rank (Except Season) + (Name)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "9d5320d5-4da4-46f0-9594-c29bc540bd73"
          },
          {
            "name": "RankOfTeam (TeamToolTip)",
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "CALCULATE([Rank (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "94bbf8a9-611c-4886-ac2f-58e3441e8428"
          },
          {
            "name": "Wins (TeamToolTip)",
            "displayFolder": "KeepFilters TeamToolTip",
            "expression": [
              "CALCULATE([Wins (Except Season)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "01b6357f-ec16-4efb-a2af-88db70cc0d4d"
          },
          {
            "name": "Rank (Except Season) + (Name)",
            "displayFolder": "Ranking With Name",
            "expression": "RANKX(ALL('Dim Team Lookup'),[TiebreakScoring (Except Season) + (Name)],,DESC,Skip)",
            "formatString": "0",
            "lineageTag": "00a8c6e1-00ac-4763-a45f-e0350aac2cb2"
          },
          {
            "name": "TiebreakScoring (Except Season) + (Name)",
            "displayFolder": "Ranking With Name",
            "expression": [
              "CALCULATE(",
              "var NumberOfRows = ",
              "ADDCOLUMNS(",
              "    'Dim Team Lookup',",
              "    \"Rank\",RANKX(ALL('Dim Team Lookup'),'Dim Team Lookup'[Team]))",
              "",
              "VAR NumberofTeams = ",
              "COUNTROWS(ALL('Dim Team Lookup'))+1",
              "",
              "VAR DecimalNumberOfRows = ",
              "DIVIDE(MAXX(NumberOfRows,[Rank]),NumberofTeams)",
              "",
              "RETURN",
              "",
              " [TiebreakScoring (Cumulative)]+DecimalNumberOfRows)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "9efc7393-6000-4404-8490-15d7868a634e"
          },
          {
            "name": "Restrict (PLT Games Played Tooltip)",
            "displayFolder": "Restrict Tooltip Measures",
            "expression": [
              "VAR BeginSeason = [Start Date Of Season]",
              "",
              "VAR CurrentDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR ENDOFSEASON = CALCULATE(MAX('Dim Calendar'[Date]), ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
              "",
              "VAR MatchesInContext = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[Match_Date],'Fact Premier League'[Result]),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] <= CurrentDate && BeginSeason <= 'Fact Premier League'[Match_Date],",
              "    REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              "",
              "VAR NextMatch = ",
              "CALCULATETABLE(",
              "SUMMARIZE('Fact Premier League','Fact Premier League'[Match Number], 'Fact Premier League'[Match_Date],'Fact Premier League'[Result]),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] > CurrentDate &&  'Fact Premier League'[Match_Date] <=ENDOFSEASON,",
              "    REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              "",
              "VAR NextMatchDate = MINX(NextMatch,[Match_Date])",
              "",
              "VAR RemovePMatches = ",
              "--FILTER(",
              "    MatchesInContext",
              "-- , [Result] <> \"P\")",
              "",
              "",
              "VAR AddRank = ",
              "ADDCOLUMNS(RemovePMatches,",
              "\"Rank\",",
              "RANKX(RemovePMatches,[Match_Date],,DESC))",
              "",
              "VAR CurrentDateValue = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Select5AddRank = ",
              "FILTER(AddRank, [Rank] <= 5)",
              "",
              "RETURN",
              "",
              "IF( CurrentDateValue IN SUMMARIZE(Select5AddRank,[Match_Date]), 1,",
              " IF( CurrentDateValue = NextMatchDate,1,0))"
            ],
            "formatString": "0",
            "lineageTag": "ed0d8188-2a32-4613-93a6-9a396bc4a003"
          },
          {
            "name": "Restrict (Position Tooltip)",
            "displayFolder": "Restrict Tooltip Measures",
            "expression": [
              "VAR TeamsInCurrentSeason = [TeamsInCurrentSeason]",
              "",
              "VAR RankOfTooltipTeam =  ",
              "CALCULATE(",
              "    [Rank (Except Season) + (Name)],",
              "    REMOVEFILTERS('Tooltip Team Lookup'))",
              "",
              "VAR AddPosition = ",
              "ADDCOLUMNS(",
              "  ALL('Tooltip Team Lookup'), ",
              "  \"Position\",",
              " [Rank with Name ('Tooltip Team Lookup')])",
              "",
              " VAR RemoveTeamsOutOfSeason = ",
              " FILTER(",
              "    AddPosition,",
              "   [Position] <= TeamsInCurrentSeason)",
              "",
              "VAR AddDiffRankPosition = ",
              "ADDCOLUMNS(",
              "  RemoveTeamsOutOfSeason,",
              "  \"Diff Rank Position\",",
              "  ABS([Position] - RankOfTooltipTeam))",
              "",
              "VAR Top5DiffRankPosition = ",
              "TOPN( 5, AddDiffRankPosition , [Diff Rank Position], ASC)",
              "",
              "",
              "  RETURN",
              "IF(HASONEVALUE('Tooltip Team Lookup'[Team]),",
              "IF(VALUES('Tooltip Team Lookup'[Team]) IN SUMMARIZE(Top5DiffRankPosition,[Team]), 1, 0))"
            ],
            "formatString": "0",
            "lineageTag": "e40f19f6-c869-47d7-b649-5f7bb42fac38"
          },
          {
            "name": "Conditional Format (Rank Cumulative) (PLT)",
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR TeamsInCurrentSeason = ",
              "CALCULATE([TeamsInCurrentSeason],REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              "",
              "VAR RelegationNumbers = ",
              "IF(SELECTEDVALUE('Dim Calendar'[Season]) = \"1994 - 95\", 4, 3)",
              "",
              "VAR RankOfTeam = [Position (PLT Games Played Toolip)]",
              "",
              "VAR RelegationTeams =",
              "RankOfTeam >",
              "(TeamsInCurrentSeason - RelegationNumbers)",
              "",
              "VAR WinningTeam = ",
              "RankOfTeam  = 1",
              "",
              "VAR RunnerUpTeam = ",
              "RankOfTeam  = 2",
              "",
              "VAR UEFAPositions = ",
              "RankOfTeam  IN {3,4}",
              "",
              "VAR ExtraUEFAPosition = ",
              "RankOfTeam  = 5",
              "",
              "RETURN",
              "IF(ISBLANK(RankOfTeam), \"White\",",
              "SWITCH(",
              "    TRUE(),",
              "    WinningTeam , \"Gold\",",
              "    RunnerUpTeam, \"Silver\",",
              "    UEFAPositions, \"Light Green\",",
              "    ExtraUEFAPosition, \"Light Blue\",",
              "    RelegationTeams, \"#F5C2C1\"))"
            ],
            "lineageTag": "b7286955-6dbe-4d6a-be40-7317b05cadee"
          },
          {
            "name": "Correct Score (PLT)",
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR Score = [Score (PLT Games Played Toolip)]",
              "RETURN",
              "IF(ISBLANK(score),\"\",",
              "\"Final Score: \"&Score)"
            ],
            "lineageTag": "7304efee-ab37-441b-952a-5763dd6d38db"
          },
          {
            "name": "Date of Match (PLT)",
            "displayFolder": "Season  (PLT)",
            "expression": "\"Date of Match: \"&FORMAT([Match Date (PLT Games Played Tooltip)], \"dd mmmm yyyy\")",
            "lineageTag": "1dd19891-a7f0-4db5-a6e7-099a8fab032b"
          },
          {
            "name": "Highlight Result for PLT Games Played Tooltip",
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR BeginSeason = [Start Date Of Season]",
              "",
              "VAR CurrentDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "   FIRSTNONBLANK('Fact Premier League'[Result],1),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] <= CurrentDate && BeginSeason <= 'Fact Premier League'[Match_Date])",
              "",
              "RETURN",
              "IF([Score (PLT Games Played Toolip)] = \"\", \t\"#066899\",",
              "SWITCH(",
              "Result,",
              "\"W\", \"rgba(77, 160, 77,1)\", ",
              "\"D\", \"rgba(117, 117, 117,1)\",",
              "\"L\", \"rgba(223, 64, 57,1)\",",
              "\"#e6ac00\"))"
            ],
            "lineageTag": "954095c8-d108-4ee7-ae03-57103218ed8e"
          },
          {
            "name": "Match Date (PLT Games Played Tooltip)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR Result = ",
              "CALCULATE(",
              "    MAX('Fact Premier League'[Match_Date]),",
              "    ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]))",
              "RETURN",
              "Result"
            ],
            "formatString": "Long Date",
            "lineageTag": "d864e63c-734d-44e9-a198-08666858b41c"
          },
          {
            "name": "Points (PLT Games Played Toolip)",
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR MaxDate = ",
              "[Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR DatesToBeSelected =",
              "FILTER(",
              "CALCULATETABLE(VALUES('Dim Calendar'[Date]), ALLEXCEPT('Dim Calendar','Dim Calendar'[Season])),",
              "'Dim Calendar'[Date] <= MaxDate)",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "   [Points],",
              "DatesToBeSelected,",
              "REMOVEFILTERS('Dim Home Team'), REMOVEFILTERS('Dim Away Team'))",
              "",
              "RETURN",
              "IF(NOT( ISBLANK([Score (PLT Games Played Toolip)]) ),Result)"
            ],
            "formatString": "0",
            "lineageTag": "4ed7ac99-77f9-46a5-bc56-b6352d07cf8a"
          },
          {
            "name": "Position (PLT Games Played Toolip)",
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR Result = ",
              "   RANKX(ALL('Dim Team Lookup'),[TiebreakScoring (Cumulative) plt],,DESC,Skip)",
              "",
              "RETURN",
              "IF(NOT ISBLANK([Score (PLT Games Played Toolip)]),Result)"
            ],
            "formatString": "0",
            "lineageTag": "39b88ed1-608b-4338-83e9-4fd0cb1c2dc3"
          },
          {
            "name": "Score (PLT Games Played Toolip)",
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR BeginSeason = [Start Date Of Season]",
              "",
              "VAR CurrentDate = MAX('Dim Calendar'[Date])",
              "",
              "VAR CurrentRowDate = [Match Date (PLT Games Played Tooltip)]",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "   FIRSTNONBLANK('Fact Premier League'[Score],1),",
              "    REMOVEFILTERS('Dim Calendar'),",
              "    'Fact Premier League'[Match_Date] <= CurrentDate && BeginSeason <= 'Fact Premier League'[Match_Date])",
              "RETURN",
              "--Result",
              "IF(",
              "BeginSeason <= CurrentRowDate && CurrentRowDate <= CurrentDate,",
              "IF(Result = \"\", \"P - P\", Result)",
              "",
              ")"
            ],
            "lineageTag": "3a58bad2-6e91-42b3-83c6-2aa85214b90b"
          },
          {
            "name": "TiebreakScoring (Cumulative) plt",
            "displayFolder": "Season  (PLT)",
            "expression": [
              "VAR MaxDate = ",
              "CALCULATE([Match Date (PLT Games Played Tooltip)], REMOVEFILTERS('Dim Team Lookup'))",
              "",
              "VAR DatesToBeSelected =",
              "FILTER(",
              "CALCULATETABLE(VALUES('Dim Calendar'[Date]), ALLEXCEPT('Dim Calendar','Dim Calendar'[Season])),",
              "'Dim Calendar'[Date] <= MaxDate)",
              "",
              "VAR LargestAbsGoalDifference = CALCULATE([Goal Scored] + [Goal Conceded],REMOVEFILTERS())",
              "",
              "VAR BaseToAdd = POWER(10,CEILING(LOG10(LargestAbsGoalDifference),1))*2",
              "",
              "VAR GD = BaseToAdd + CALCULATE([Goal Difference],DatesToBeSelected, REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              "",
              "VAR GS = BaseToAdd + CALCULATE([Goal Scored],DatesToBeSelected, REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              " ",
              "VAR Points = CALCULATE([Points],DatesToBeSelected,REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team')) + ABS(CALCULATE([Penalty Points],REMOVEFILTERS()))",
              "",
              "VAR GamesThisSeason = ",
              "CALCULATE([Games Played],ALLEXCEPT('Dim Calendar','Dim Calendar'[Season]), REMOVEFILTERS('Dim Match Number'), REMOVEFILTERS('Dim Away Team'), REMOVEFILTERS('Dim Home Team'))",
              "",
              "RETURN",
              "IF( GamesThisSeason,",
              "    INT(Points&GD&GS)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9f381908-667f-46d6-9d97-a269e1438b5e"
          },
          {
            "name": "TiebreakScoring AllEXCEPT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE(",
              "[TiebreakScoring (Except Season) + (Name)],",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "lineageTag": "6da85fb5-5aab-4ec5-9997-58304e0ec89b"
          },
          {
            "name": "Highlight Result for RbMN Games Played Tooltip",
            "displayFolder": "ToolTip Display Measures",
            "expression": [
              "SWITCH(",
              "LASTNONBLANK('Fact Premier League'[Result],1),",
              "\"W\", \"#4DA04D\",",
              "\"D\", \"#757575\",",
              "\"L\", \"#DF4039\")"
            ],
            "lineageTag": "c7df0a90-bc55-4b3c-81e8-878ab381c432"
          },
          {
            "name": "Highlight Team for Position Tooltip",
            "displayFolder": "ToolTip Display Measures",
            "expression": "IF([Games Played (End of Season)],\"lIGHT BLUE\")",
            "lineageTag": "6c58f2b3-5fac-47c2-b156-e038eceff715"
          },
          {
            "name": "Draws ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE([Draws (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "48be2517-7024-417d-aa3f-8a605603ee87"
          },
          {
            "name": "Games Played ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE([Games Played (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "1c07c161-a12f-40be-9406-0f05eca43d34"
          },
          {
            "name": "Goal Difference ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE([Goal Difference (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "f14ef1a0-b049-4a84-a740-01d17253148d"
          },
          {
            "name": "Losses ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE([Losses (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "b7be54da-80a2-4853-9ead-bad3985c7d92"
          },
          {
            "name": "Points ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE([Points (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "02332242-cd11-49c7-b0f6-2319d0f02798"
          },
          {
            "name": "Rank with Name ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "VAR SelectedHomeAway = SELECTEDVALUE('Dim H-A'[Home / Away])",
              "",
              "RETURN",
              "",
              "CALCULATE([Rank (Except Season) + (Name)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "a4d5a43a-5524-4ea0-8b2d-e59f16496cfb"
          },
          {
            "name": "RankOfTeam ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE([Rank (Cumulative)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "173dfb55-4376-4d07-9e89-17f5f085504f"
          },
          {
            "name": "Wins ('Tooltip Team Lookup')",
            "displayFolder": "Tooltip (AllExcept) Measures",
            "expression": [
              "CALCULATE([Wins (Except Season)], ",
              "ALLEXCEPT('Dim Team Lookup','Tooltip Team Lookup'))"
            ],
            "formatString": "0",
            "lineageTag": "66bc42a2-d1b9-4000-b680-bf8bd5016cad"
          }
        ],
        "partitions": [
          {
            "name": "Tooltip Team Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"pdsgmbbd3g4utlpt3pbecxmkb4-untjprzqj7juhfbm2h5e5bfwju.datawarehouse.fabric.microsoft.com\"),",
                "    #\"Premier League Dataset\" = Source{[Name=\"Premier League Dataset\"]}[Data],",
                "    #\"dbo_Tooltip Team Lookup\" = #\"Premier League Dataset\"{[Schema=\"dbo\",Item=\"Tooltip Team Lookup\"]}[Data]",
                "in",
                "    #\"dbo_Tooltip Team Lookup\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}